// Code generated by ent, DO NOT EDIT.

package candidatesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldLTE(FieldID, id))
}

// ObservedAt applies equality check predicate on the "observed_at" field. It's identical to ObservedAtEQ.
func ObservedAt(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldEQ(FieldObservedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// ObservedAtEQ applies the EQ predicate on the "observed_at" field.
func ObservedAtEQ(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldEQ(FieldObservedAt, v))
}

// ObservedAtNEQ applies the NEQ predicate on the "observed_at" field.
func ObservedAtNEQ(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldNEQ(FieldObservedAt, v))
}

// ObservedAtIn applies the In predicate on the "observed_at" field.
func ObservedAtIn(vs ...time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldIn(FieldObservedAt, vs...))
}

// ObservedAtNotIn applies the NotIn predicate on the "observed_at" field.
func ObservedAtNotIn(vs ...time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldNotIn(FieldObservedAt, vs...))
}

// ObservedAtGT applies the GT predicate on the "observed_at" field.
func ObservedAtGT(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldGT(FieldObservedAt, v))
}

// ObservedAtGTE applies the GTE predicate on the "observed_at" field.
func ObservedAtGTE(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldGTE(FieldObservedAt, v))
}

// ObservedAtLT applies the LT predicate on the "observed_at" field.
func ObservedAtLT(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldLT(FieldObservedAt, v))
}

// ObservedAtLTE applies the LTE predicate on the "observed_at" field.
func ObservedAtLTE(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldLTE(FieldObservedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// HasCandidate applies the HasEdge predicate on the "candidate" edge.
func HasCandidate() predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CandidateTable, CandidateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCandidateWith applies the HasEdge predicate on the "candidate" edge with a given conditions (other predicates).
func HasCandidateWith(preds ...predicate.Candidate) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(func(s *sql.Selector) {
		step := newCandidateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CandidateSnapshot) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CandidateSnapshot) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CandidateSnapshot) predicate.CandidateSnapshot {
	return predicate.CandidateSnapshot(sql.NotPredicates(p))
}
