// Code generated by ent, DO NOT EDIT.

package candidate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Candidate {
	return predicate.Candidate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Candidate {
	return predicate.Candidate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Candidate {
	return predicate.Candidate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Candidate {
	return predicate.Candidate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Candidate {
	return predicate.Candidate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Candidate {
	return predicate.Candidate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Candidate {
	return predicate.Candidate(sql.FieldLTE(FieldID, id))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldNetwork, v))
}

// MintAddress applies equality check predicate on the "mint_address" field. It's identical to MintAddressEQ.
func MintAddress(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldMintAddress, v))
}

// PoolAddress applies equality check predicate on the "pool_address" field. It's identical to PoolAddressEQ.
func PoolAddress(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldPoolAddress, v))
}

// DiscoveredAt applies equality check predicate on the "discovered_at" field. It's identical to DiscoveredAtEQ.
func DiscoveredAt(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldDiscoveredAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldUpdatedAt, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.Candidate {
	return predicate.Candidate(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.Candidate {
	return predicate.Candidate(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldContainsFold(FieldNetwork, v))
}

// MintAddressEQ applies the EQ predicate on the "mint_address" field.
func MintAddressEQ(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldMintAddress, v))
}

// MintAddressNEQ applies the NEQ predicate on the "mint_address" field.
func MintAddressNEQ(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldNEQ(FieldMintAddress, v))
}

// MintAddressIn applies the In predicate on the "mint_address" field.
func MintAddressIn(vs ...string) predicate.Candidate {
	return predicate.Candidate(sql.FieldIn(FieldMintAddress, vs...))
}

// MintAddressNotIn applies the NotIn predicate on the "mint_address" field.
func MintAddressNotIn(vs ...string) predicate.Candidate {
	return predicate.Candidate(sql.FieldNotIn(FieldMintAddress, vs...))
}

// MintAddressGT applies the GT predicate on the "mint_address" field.
func MintAddressGT(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldGT(FieldMintAddress, v))
}

// MintAddressGTE applies the GTE predicate on the "mint_address" field.
func MintAddressGTE(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldGTE(FieldMintAddress, v))
}

// MintAddressLT applies the LT predicate on the "mint_address" field.
func MintAddressLT(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldLT(FieldMintAddress, v))
}

// MintAddressLTE applies the LTE predicate on the "mint_address" field.
func MintAddressLTE(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldLTE(FieldMintAddress, v))
}

// MintAddressContains applies the Contains predicate on the "mint_address" field.
func MintAddressContains(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldContains(FieldMintAddress, v))
}

// MintAddressHasPrefix applies the HasPrefix predicate on the "mint_address" field.
func MintAddressHasPrefix(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldHasPrefix(FieldMintAddress, v))
}

// MintAddressHasSuffix applies the HasSuffix predicate on the "mint_address" field.
func MintAddressHasSuffix(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldHasSuffix(FieldMintAddress, v))
}

// MintAddressEqualFold applies the EqualFold predicate on the "mint_address" field.
func MintAddressEqualFold(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldEqualFold(FieldMintAddress, v))
}

// MintAddressContainsFold applies the ContainsFold predicate on the "mint_address" field.
func MintAddressContainsFold(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldContainsFold(FieldMintAddress, v))
}

// PoolAddressEQ applies the EQ predicate on the "pool_address" field.
func PoolAddressEQ(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldPoolAddress, v))
}

// PoolAddressNEQ applies the NEQ predicate on the "pool_address" field.
func PoolAddressNEQ(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldNEQ(FieldPoolAddress, v))
}

// PoolAddressIn applies the In predicate on the "pool_address" field.
func PoolAddressIn(vs ...string) predicate.Candidate {
	return predicate.Candidate(sql.FieldIn(FieldPoolAddress, vs...))
}

// PoolAddressNotIn applies the NotIn predicate on the "pool_address" field.
func PoolAddressNotIn(vs ...string) predicate.Candidate {
	return predicate.Candidate(sql.FieldNotIn(FieldPoolAddress, vs...))
}

// PoolAddressGT applies the GT predicate on the "pool_address" field.
func PoolAddressGT(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldGT(FieldPoolAddress, v))
}

// PoolAddressGTE applies the GTE predicate on the "pool_address" field.
func PoolAddressGTE(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldGTE(FieldPoolAddress, v))
}

// PoolAddressLT applies the LT predicate on the "pool_address" field.
func PoolAddressLT(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldLT(FieldPoolAddress, v))
}

// PoolAddressLTE applies the LTE predicate on the "pool_address" field.
func PoolAddressLTE(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldLTE(FieldPoolAddress, v))
}

// PoolAddressContains applies the Contains predicate on the "pool_address" field.
func PoolAddressContains(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldContains(FieldPoolAddress, v))
}

// PoolAddressHasPrefix applies the HasPrefix predicate on the "pool_address" field.
func PoolAddressHasPrefix(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldHasPrefix(FieldPoolAddress, v))
}

// PoolAddressHasSuffix applies the HasSuffix predicate on the "pool_address" field.
func PoolAddressHasSuffix(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldHasSuffix(FieldPoolAddress, v))
}

// PoolAddressEqualFold applies the EqualFold predicate on the "pool_address" field.
func PoolAddressEqualFold(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldEqualFold(FieldPoolAddress, v))
}

// PoolAddressContainsFold applies the ContainsFold predicate on the "pool_address" field.
func PoolAddressContainsFold(v string) predicate.Candidate {
	return predicate.Candidate(sql.FieldContainsFold(FieldPoolAddress, v))
}

// DiscoveredAtEQ applies the EQ predicate on the "discovered_at" field.
func DiscoveredAtEQ(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldDiscoveredAt, v))
}

// DiscoveredAtNEQ applies the NEQ predicate on the "discovered_at" field.
func DiscoveredAtNEQ(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldNEQ(FieldDiscoveredAt, v))
}

// DiscoveredAtIn applies the In predicate on the "discovered_at" field.
func DiscoveredAtIn(vs ...time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldIn(FieldDiscoveredAt, vs...))
}

// DiscoveredAtNotIn applies the NotIn predicate on the "discovered_at" field.
func DiscoveredAtNotIn(vs ...time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldNotIn(FieldDiscoveredAt, vs...))
}

// DiscoveredAtGT applies the GT predicate on the "discovered_at" field.
func DiscoveredAtGT(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldGT(FieldDiscoveredAt, v))
}

// DiscoveredAtGTE applies the GTE predicate on the "discovered_at" field.
func DiscoveredAtGTE(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldGTE(FieldDiscoveredAt, v))
}

// DiscoveredAtLT applies the LT predicate on the "discovered_at" field.
func DiscoveredAtLT(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldLT(FieldDiscoveredAt, v))
}

// DiscoveredAtLTE applies the LTE predicate on the "discovered_at" field.
func DiscoveredAtLTE(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldLTE(FieldDiscoveredAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Candidate {
	return predicate.Candidate(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSnapshots applies the HasEdge predicate on the "snapshots" edge.
func HasSnapshots() predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotsWith applies the HasEdge predicate on the "snapshots" edge with a given conditions (other predicates).
func HasSnapshotsWith(preds ...predicate.CandidateSnapshot) predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := newSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSocialSnapshots applies the HasEdge predicate on the "social_snapshots" edge.
func HasSocialSnapshots() predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SocialSnapshotsTable, SocialSnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSocialSnapshotsWith applies the HasEdge predicate on the "social_snapshots" edge with a given conditions (other predicates).
func HasSocialSnapshotsWith(preds ...predicate.SocialSnapshot) predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := newSocialSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVerdicts applies the HasEdge predicate on the "verdicts" edge.
func HasVerdicts() predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VerdictsTable, VerdictsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVerdictsWith applies the HasEdge predicate on the "verdicts" edge with a given conditions (other predicates).
func HasVerdictsWith(preds ...predicate.Verdict) predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := newVerdictsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDecisions applies the HasEdge predicate on the "decisions" edge.
func HasDecisions() predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DecisionsTable, DecisionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDecisionsWith applies the HasEdge predicate on the "decisions" edge with a given conditions (other predicates).
func HasDecisionsWith(preds ...predicate.TradeDecision) predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := newDecisionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPositions applies the HasEdge predicate on the "positions" edge.
func HasPositions() predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PositionsTable, PositionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPositionsWith applies the HasEdge predicate on the "positions" edge with a given conditions (other predicates).
func HasPositionsWith(preds ...predicate.PaperPosition) predicate.Candidate {
	return predicate.Candidate(func(s *sql.Selector) {
		step := newPositionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Candidate) predicate.Candidate {
	return predicate.Candidate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Candidate) predicate.Candidate {
	return predicate.Candidate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Candidate) predicate.Candidate {
	return predicate.Candidate(sql.NotPredicates(p))
}
