// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/apiusage"
)

// APIUsageCreate is the builder for creating a APIUsage entity.
type APIUsageCreate struct {
	config
	mutation *APIUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProvider sets the "provider" field.
func (_c *APIUsageCreate) SetProvider(v string) *APIUsageCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetUtcDate sets the "utc_date" field.
func (_c *APIUsageCreate) SetUtcDate(v time.Time) *APIUsageCreate {
	_c.mutation.SetUtcDate(v)
	return _c
}

// SetRequestCount sets the "request_count" field.
func (_c *APIUsageCreate) SetRequestCount(v int) *APIUsageCreate {
	_c.mutation.SetRequestCount(v)
	return _c
}

// SetFailureCount sets the "failure_count" field.
func (_c *APIUsageCreate) SetFailureCount(v int) *APIUsageCreate {
	_c.mutation.SetFailureCount(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIUsageCreate) SetCreatedAt(v time.Time) *APIUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIUsageCreate) SetNillableCreatedAt(v *time.Time) *APIUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIUsageCreate) SetUpdatedAt(v time.Time) *APIUsageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIUsageCreate) SetNillableUpdatedAt(v *time.Time) *APIUsageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the APIUsageMutation object of the builder.
func (_c *APIUsageCreate) Mutation() *APIUsageMutation {
	return _c.mutation
}

// Save creates the APIUsage in the database.
func (_c *APIUsageCreate) Save(ctx context.Context) (*APIUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIUsageCreate) SaveX(ctx context.Context) *APIUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIUsageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apiusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apiusage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIUsageCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "APIUsage.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := apiusage.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "APIUsage.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UtcDate(); !ok {
		return &ValidationError{Name: "utc_date", err: errors.New(`ent: missing required field "APIUsage.utc_date"`)}
	}
	if _, ok := _c.mutation.RequestCount(); !ok {
		return &ValidationError{Name: "request_count", err: errors.New(`ent: missing required field "APIUsage.request_count"`)}
	}
	if v, ok := _c.mutation.RequestCount(); ok {
		if err := apiusage.RequestCountValidator(v); err != nil {
			return &ValidationError{Name: "request_count", err: fmt.Errorf(`ent: validator failed for field "APIUsage.request_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "APIUsage.failure_count"`)}
	}
	if v, ok := _c.mutation.FailureCount(); ok {
		if err := apiusage.FailureCountValidator(v); err != nil {
			return &ValidationError{Name: "failure_count", err: fmt.Errorf(`ent: validator failed for field "APIUsage.failure_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIUsage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIUsage.updated_at"`)}
	}
	return nil
}

func (_c *APIUsageCreate) sqlSave(ctx context.Context) (*APIUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIUsageCreate) createSpec() (*APIUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &APIUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apiusage.Table, sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(apiusage.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.UtcDate(); ok {
		_spec.SetField(apiusage.FieldUtcDate, field.TypeTime, value)
		_node.UtcDate = value
	}
	if value, ok := _c.mutation.RequestCount(); ok {
		_spec.SetField(apiusage.FieldRequestCount, field.TypeInt, value)
		_node.RequestCount = value
	}
	if value, ok := _c.mutation.FailureCount(); ok {
		_spec.SetField(apiusage.FieldFailureCount, field.TypeInt, value)
		_node.FailureCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apiusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apiusage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIUsage.Create().
//		SetProvider(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIUsageUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *APIUsageCreate) OnConflict(opts ...sql.ConflictOption) *APIUsageUpsertOne {
	_c.conflict = opts
	return &APIUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIUsageCreate) OnConflictColumns(columns ...string) *APIUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIUsageUpsertOne{
		create: _c,
	}
}

type (
	// APIUsageUpsertOne is the builder for "upsert"-ing
	//  one APIUsage node.
	APIUsageUpsertOne struct {
		create *APIUsageCreate
	}

	// APIUsageUpsert is the "OnConflict" setter.
	APIUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetProvider sets the "provider" field.
func (u *APIUsageUpsert) SetProvider(v string) *APIUsageUpsert {
	u.Set(apiusage.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *APIUsageUpsert) UpdateProvider() *APIUsageUpsert {
	u.SetExcluded(apiusage.FieldProvider)
	return u
}

// SetUtcDate sets the "utc_date" field.
func (u *APIUsageUpsert) SetUtcDate(v time.Time) *APIUsageUpsert {
	u.Set(apiusage.FieldUtcDate, v)
	return u
}

// UpdateUtcDate sets the "utc_date" field to the value that was provided on create.
func (u *APIUsageUpsert) UpdateUtcDate() *APIUsageUpsert {
	u.SetExcluded(apiusage.FieldUtcDate)
	return u
}

// SetRequestCount sets the "request_count" field.
func (u *APIUsageUpsert) SetRequestCount(v int) *APIUsageUpsert {
	u.Set(apiusage.FieldRequestCount, v)
	return u
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *APIUsageUpsert) UpdateRequestCount() *APIUsageUpsert {
	u.SetExcluded(apiusage.FieldRequestCount)
	return u
}

// AddRequestCount adds v to the "request_count" field.
func (u *APIUsageUpsert) AddRequestCount(v int) *APIUsageUpsert {
	u.Add(apiusage.FieldRequestCount, v)
	return u
}

// SetFailureCount sets the "failure_count" field.
func (u *APIUsageUpsert) SetFailureCount(v int) *APIUsageUpsert {
	u.Set(apiusage.FieldFailureCount, v)
	return u
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *APIUsageUpsert) UpdateFailureCount() *APIUsageUpsert {
	u.SetExcluded(apiusage.FieldFailureCount)
	return u
}

// AddFailureCount adds v to the "failure_count" field.
func (u *APIUsageUpsert) AddFailureCount(v int) *APIUsageUpsert {
	u.Add(apiusage.FieldFailureCount, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIUsageUpsert) SetUpdatedAt(v time.Time) *APIUsageUpsert {
	u.Set(apiusage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIUsageUpsert) UpdateUpdatedAt() *APIUsageUpsert {
	u.SetExcluded(apiusage.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIUsageUpsertOne) UpdateNewValues() *APIUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apiusage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIUsageUpsertOne) Ignore() *APIUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIUsageUpsertOne) DoNothing() *APIUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIUsageCreate.OnConflict
// documentation for more info.
func (u *APIUsageUpsertOne) Update(set func(*APIUsageUpsert)) *APIUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *APIUsageUpsertOne) SetProvider(v string) *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *APIUsageUpsertOne) UpdateProvider() *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateProvider()
	})
}

// SetUtcDate sets the "utc_date" field.
func (u *APIUsageUpsertOne) SetUtcDate(v time.Time) *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetUtcDate(v)
	})
}

// UpdateUtcDate sets the "utc_date" field to the value that was provided on create.
func (u *APIUsageUpsertOne) UpdateUtcDate() *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateUtcDate()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *APIUsageUpsertOne) SetRequestCount(v int) *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *APIUsageUpsertOne) AddRequestCount(v int) *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *APIUsageUpsertOne) UpdateRequestCount() *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateRequestCount()
	})
}

// SetFailureCount sets the "failure_count" field.
func (u *APIUsageUpsertOne) SetFailureCount(v int) *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetFailureCount(v)
	})
}

// AddFailureCount adds v to the "failure_count" field.
func (u *APIUsageUpsertOne) AddFailureCount(v int) *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.AddFailureCount(v)
	})
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *APIUsageUpsertOne) UpdateFailureCount() *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateFailureCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIUsageUpsertOne) SetUpdatedAt(v time.Time) *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIUsageUpsertOne) UpdateUpdatedAt() *APIUsageUpsertOne {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *APIUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIUsageUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIUsageUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIUsageCreateBulk is the builder for creating many APIUsage entities in bulk.
type APIUsageCreateBulk struct {
	config
	err      error
	builders []*APIUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the APIUsage entities in the database.
func (_c *APIUsageCreateBulk) Save(ctx context.Context) ([]*APIUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIUsageCreateBulk) SaveX(ctx context.Context) []*APIUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIUsageUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *APIUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIUsageUpsertBulk {
	_c.conflict = opts
	return &APIUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIUsageCreateBulk) OnConflictColumns(columns ...string) *APIUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIUsageUpsertBulk{
		create: _c,
	}
}

// APIUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of APIUsage nodes.
type APIUsageUpsertBulk struct {
	create *APIUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIUsageUpsertBulk) UpdateNewValues() *APIUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apiusage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIUsageUpsertBulk) Ignore() *APIUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIUsageUpsertBulk) DoNothing() *APIUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIUsageCreateBulk.OnConflict
// documentation for more info.
func (u *APIUsageUpsertBulk) Update(set func(*APIUsageUpsert)) *APIUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *APIUsageUpsertBulk) SetProvider(v string) *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *APIUsageUpsertBulk) UpdateProvider() *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateProvider()
	})
}

// SetUtcDate sets the "utc_date" field.
func (u *APIUsageUpsertBulk) SetUtcDate(v time.Time) *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetUtcDate(v)
	})
}

// UpdateUtcDate sets the "utc_date" field to the value that was provided on create.
func (u *APIUsageUpsertBulk) UpdateUtcDate() *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateUtcDate()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *APIUsageUpsertBulk) SetRequestCount(v int) *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *APIUsageUpsertBulk) AddRequestCount(v int) *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *APIUsageUpsertBulk) UpdateRequestCount() *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateRequestCount()
	})
}

// SetFailureCount sets the "failure_count" field.
func (u *APIUsageUpsertBulk) SetFailureCount(v int) *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetFailureCount(v)
	})
}

// AddFailureCount adds v to the "failure_count" field.
func (u *APIUsageUpsertBulk) AddFailureCount(v int) *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.AddFailureCount(v)
	})
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *APIUsageUpsertBulk) UpdateFailureCount() *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateFailureCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIUsageUpsertBulk) SetUpdatedAt(v time.Time) *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIUsageUpsertBulk) UpdateUpdatedAt() *APIUsageUpsertBulk {
	return u.Update(func(s *APIUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *APIUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
