// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/botstate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
)

// BotStateUpdate is the builder for updating BotState entities.
type BotStateUpdate struct {
	config
	hooks    []Hook
	mutation *BotStateMutation
}

// Where appends a list predicates to the BotStateUpdate builder.
func (_u *BotStateUpdate) Where(ps ...predicate.BotState) *BotStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStateKey sets the "state_key" field.
func (_u *BotStateUpdate) SetStateKey(v string) *BotStateUpdate {
	_u.mutation.SetStateKey(v)
	return _u
}

// SetNillableStateKey sets the "state_key" field if the given value is not nil.
func (_u *BotStateUpdate) SetNillableStateKey(v *string) *BotStateUpdate {
	if v != nil {
		_u.SetStateKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *BotStateUpdate) SetValue(v map[string]interface{}) *BotStateUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BotStateUpdate) SetUpdatedAt(v time.Time) *BotStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BotStateMutation object of the builder.
func (_u *BotStateUpdate) Mutation() *BotStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BotStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BotStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BotStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BotStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BotStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := botstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BotStateUpdate) check() error {
	if v, ok := _u.mutation.StateKey(); ok {
		if err := botstate.StateKeyValidator(v); err != nil {
			return &ValidationError{Name: "state_key", err: fmt.Errorf(`ent: validator failed for field "BotState.state_key": %w`, err)}
		}
	}
	return nil
}

func (_u *BotStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(botstate.Table, botstate.Columns, sqlgraph.NewFieldSpec(botstate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StateKey(); ok {
		_spec.SetField(botstate.FieldStateKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(botstate.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(botstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{botstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BotStateUpdateOne is the builder for updating a single BotState entity.
type BotStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BotStateMutation
}

// SetStateKey sets the "state_key" field.
func (_u *BotStateUpdateOne) SetStateKey(v string) *BotStateUpdateOne {
	_u.mutation.SetStateKey(v)
	return _u
}

// SetNillableStateKey sets the "state_key" field if the given value is not nil.
func (_u *BotStateUpdateOne) SetNillableStateKey(v *string) *BotStateUpdateOne {
	if v != nil {
		_u.SetStateKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *BotStateUpdateOne) SetValue(v map[string]interface{}) *BotStateUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BotStateUpdateOne) SetUpdatedAt(v time.Time) *BotStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BotStateMutation object of the builder.
func (_u *BotStateUpdateOne) Mutation() *BotStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the BotStateUpdate builder.
func (_u *BotStateUpdateOne) Where(ps ...predicate.BotState) *BotStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BotStateUpdateOne) Select(field string, fields ...string) *BotStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BotState entity.
func (_u *BotStateUpdateOne) Save(ctx context.Context) (*BotState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BotStateUpdateOne) SaveX(ctx context.Context) *BotState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BotStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BotStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BotStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := botstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BotStateUpdateOne) check() error {
	if v, ok := _u.mutation.StateKey(); ok {
		if err := botstate.StateKeyValidator(v); err != nil {
			return &ValidationError{Name: "state_key", err: fmt.Errorf(`ent: validator failed for field "BotState.state_key": %w`, err)}
		}
	}
	return nil
}

func (_u *BotStateUpdateOne) sqlSave(ctx context.Context) (_node *BotState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(botstate.Table, botstate.Columns, sqlgraph.NewFieldSpec(botstate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BotState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, botstate.FieldID)
		for _, f := range fields {
			if !botstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != botstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StateKey(); ok {
		_spec.SetField(botstate.FieldStateKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(botstate.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(botstate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &BotState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{botstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
