// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidatesnapshot"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/socialsnapshot"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/tradedecision"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/verdict"
)

// CandidateQuery is the builder for querying Candidate entities.
type CandidateQuery struct {
	config
	ctx                 *QueryContext
	order               []candidate.OrderOption
	inters              []Interceptor
	predicates          []predicate.Candidate
	withSnapshots       *CandidateSnapshotQuery
	withSocialSnapshots *SocialSnapshotQuery
	withVerdicts        *VerdictQuery
	withDecisions       *TradeDecisionQuery
	withPositions       *PaperPositionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CandidateQuery builder.
func (_q *CandidateQuery) Where(ps ...predicate.Candidate) *CandidateQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CandidateQuery) Limit(limit int) *CandidateQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CandidateQuery) Offset(offset int) *CandidateQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CandidateQuery) Unique(unique bool) *CandidateQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CandidateQuery) Order(o ...candidate.OrderOption) *CandidateQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySnapshots chains the current query on the "snapshots" edge.
func (_q *CandidateQuery) QuerySnapshots() *CandidateSnapshotQuery {
	query := (&CandidateSnapshotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(candidate.Table, candidate.FieldID, selector),
			sqlgraph.To(candidatesnapshot.Table, candidatesnapshot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, candidate.SnapshotsTable, candidate.SnapshotsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySocialSnapshots chains the current query on the "social_snapshots" edge.
func (_q *CandidateQuery) QuerySocialSnapshots() *SocialSnapshotQuery {
	query := (&SocialSnapshotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(candidate.Table, candidate.FieldID, selector),
			sqlgraph.To(socialsnapshot.Table, socialsnapshot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, candidate.SocialSnapshotsTable, candidate.SocialSnapshotsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVerdicts chains the current query on the "verdicts" edge.
func (_q *CandidateQuery) QueryVerdicts() *VerdictQuery {
	query := (&VerdictClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(candidate.Table, candidate.FieldID, selector),
			sqlgraph.To(verdict.Table, verdict.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, candidate.VerdictsTable, candidate.VerdictsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDecisions chains the current query on the "decisions" edge.
func (_q *CandidateQuery) QueryDecisions() *TradeDecisionQuery {
	query := (&TradeDecisionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(candidate.Table, candidate.FieldID, selector),
			sqlgraph.To(tradedecision.Table, tradedecision.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, candidate.DecisionsTable, candidate.DecisionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPositions chains the current query on the "positions" edge.
func (_q *CandidateQuery) QueryPositions() *PaperPositionQuery {
	query := (&PaperPositionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(candidate.Table, candidate.FieldID, selector),
			sqlgraph.To(paperposition.Table, paperposition.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, candidate.PositionsTable, candidate.PositionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Candidate entity from the query.
// Returns a *NotFoundError when no Candidate was found.
func (_q *CandidateQuery) First(ctx context.Context) (*Candidate, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{candidate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CandidateQuery) FirstX(ctx context.Context) *Candidate {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Candidate ID from the query.
// Returns a *NotFoundError when no Candidate ID was found.
func (_q *CandidateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{candidate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CandidateQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Candidate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Candidate entity is found.
// Returns a *NotFoundError when no Candidate entities are found.
func (_q *CandidateQuery) Only(ctx context.Context) (*Candidate, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{candidate.Label}
	default:
		return nil, &NotSingularError{candidate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CandidateQuery) OnlyX(ctx context.Context) *Candidate {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Candidate ID in the query.
// Returns a *NotSingularError when more than one Candidate ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CandidateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{candidate.Label}
	default:
		err = &NotSingularError{candidate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CandidateQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Candidates.
func (_q *CandidateQuery) All(ctx context.Context) ([]*Candidate, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Candidate, *CandidateQuery]()
	return withInterceptors[[]*Candidate](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CandidateQuery) AllX(ctx context.Context) []*Candidate {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Candidate IDs.
func (_q *CandidateQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(candidate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CandidateQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CandidateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CandidateQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CandidateQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CandidateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CandidateQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CandidateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CandidateQuery) Clone() *CandidateQuery {
	if _q == nil {
		return nil
	}
	return &CandidateQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]candidate.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.Candidate{}, _q.predicates...),
		withSnapshots:       _q.withSnapshots.Clone(),
		withSocialSnapshots: _q.withSocialSnapshots.Clone(),
		withVerdicts:        _q.withVerdicts.Clone(),
		withDecisions:       _q.withDecisions.Clone(),
		withPositions:       _q.withPositions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSnapshots tells the query-builder to eager-load the nodes that are connected to
// the "snapshots" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CandidateQuery) WithSnapshots(opts ...func(*CandidateSnapshotQuery)) *CandidateQuery {
	query := (&CandidateSnapshotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSnapshots = query
	return _q
}

// WithSocialSnapshots tells the query-builder to eager-load the nodes that are connected to
// the "social_snapshots" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CandidateQuery) WithSocialSnapshots(opts ...func(*SocialSnapshotQuery)) *CandidateQuery {
	query := (&SocialSnapshotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSocialSnapshots = query
	return _q
}

// WithVerdicts tells the query-builder to eager-load the nodes that are connected to
// the "verdicts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CandidateQuery) WithVerdicts(opts ...func(*VerdictQuery)) *CandidateQuery {
	query := (&VerdictClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVerdicts = query
	return _q
}

// WithDecisions tells the query-builder to eager-load the nodes that are connected to
// the "decisions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CandidateQuery) WithDecisions(opts ...func(*TradeDecisionQuery)) *CandidateQuery {
	query := (&TradeDecisionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDecisions = query
	return _q
}

// WithPositions tells the query-builder to eager-load the nodes that are connected to
// the "positions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CandidateQuery) WithPositions(opts ...func(*PaperPositionQuery)) *CandidateQuery {
	query := (&PaperPositionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPositions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Network string `json:"network,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Candidate.Query().
//		GroupBy(candidate.FieldNetwork).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CandidateQuery) GroupBy(field string, fields ...string) *CandidateGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CandidateGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = candidate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Network string `json:"network,omitempty"`
//	}
//
//	client.Candidate.Query().
//		Select(candidate.FieldNetwork).
//		Scan(ctx, &v)
func (_q *CandidateQuery) Select(fields ...string) *CandidateSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CandidateSelect{CandidateQuery: _q}
	sbuild.label = candidate.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CandidateSelect configured with the given aggregations.
func (_q *CandidateQuery) Aggregate(fns ...AggregateFunc) *CandidateSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CandidateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !candidate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CandidateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Candidate, error) {
	var (
		nodes       = []*Candidate{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withSnapshots != nil,
			_q.withSocialSnapshots != nil,
			_q.withVerdicts != nil,
			_q.withDecisions != nil,
			_q.withPositions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Candidate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Candidate{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSnapshots; query != nil {
		if err := _q.loadSnapshots(ctx, query, nodes,
			func(n *Candidate) { n.Edges.Snapshots = []*CandidateSnapshot{} },
			func(n *Candidate, e *CandidateSnapshot) { n.Edges.Snapshots = append(n.Edges.Snapshots, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSocialSnapshots; query != nil {
		if err := _q.loadSocialSnapshots(ctx, query, nodes,
			func(n *Candidate) { n.Edges.SocialSnapshots = []*SocialSnapshot{} },
			func(n *Candidate, e *SocialSnapshot) { n.Edges.SocialSnapshots = append(n.Edges.SocialSnapshots, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVerdicts; query != nil {
		if err := _q.loadVerdicts(ctx, query, nodes,
			func(n *Candidate) { n.Edges.Verdicts = []*Verdict{} },
			func(n *Candidate, e *Verdict) { n.Edges.Verdicts = append(n.Edges.Verdicts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDecisions; query != nil {
		if err := _q.loadDecisions(ctx, query, nodes,
			func(n *Candidate) { n.Edges.Decisions = []*TradeDecision{} },
			func(n *Candidate, e *TradeDecision) { n.Edges.Decisions = append(n.Edges.Decisions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPositions; query != nil {
		if err := _q.loadPositions(ctx, query, nodes,
			func(n *Candidate) { n.Edges.Positions = []*PaperPosition{} },
			func(n *Candidate, e *PaperPosition) { n.Edges.Positions = append(n.Edges.Positions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CandidateQuery) loadSnapshots(ctx context.Context, query *CandidateSnapshotQuery, nodes []*Candidate, init func(*Candidate), assign func(*Candidate, *CandidateSnapshot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Candidate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CandidateSnapshot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(candidate.SnapshotsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.candidate_snapshots
		if fk == nil {
			return fmt.Errorf(`foreign-key "candidate_snapshots" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "candidate_snapshots" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CandidateQuery) loadSocialSnapshots(ctx context.Context, query *SocialSnapshotQuery, nodes []*Candidate, init func(*Candidate), assign func(*Candidate, *SocialSnapshot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Candidate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.SocialSnapshot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(candidate.SocialSnapshotsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.candidate_social_snapshots
		if fk == nil {
			return fmt.Errorf(`foreign-key "candidate_social_snapshots" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "candidate_social_snapshots" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CandidateQuery) loadVerdicts(ctx context.Context, query *VerdictQuery, nodes []*Candidate, init func(*Candidate), assign func(*Candidate, *Verdict)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Candidate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Verdict(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(candidate.VerdictsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.candidate_verdicts
		if fk == nil {
			return fmt.Errorf(`foreign-key "candidate_verdicts" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "candidate_verdicts" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CandidateQuery) loadDecisions(ctx context.Context, query *TradeDecisionQuery, nodes []*Candidate, init func(*Candidate), assign func(*Candidate, *TradeDecision)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Candidate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.TradeDecision(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(candidate.DecisionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.candidate_decisions
		if fk == nil {
			return fmt.Errorf(`foreign-key "candidate_decisions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "candidate_decisions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CandidateQuery) loadPositions(ctx context.Context, query *PaperPositionQuery, nodes []*Candidate, init func(*Candidate), assign func(*Candidate, *PaperPosition)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Candidate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PaperPosition(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(candidate.PositionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.candidate_positions
		if fk == nil {
			return fmt.Errorf(`foreign-key "candidate_positions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "candidate_positions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CandidateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CandidateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(candidate.Table, candidate.Columns, sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, candidate.FieldID)
		for i := range fields {
			if fields[i] != candidate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CandidateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(candidate.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = candidate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CandidateGroupBy is the group-by builder for Candidate entities.
type CandidateGroupBy struct {
	selector
	build *CandidateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CandidateGroupBy) Aggregate(fns ...AggregateFunc) *CandidateGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CandidateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CandidateQuery, *CandidateGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CandidateGroupBy) sqlScan(ctx context.Context, root *CandidateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CandidateSelect is the builder for selecting fields of Candidate entities.
type CandidateSelect struct {
	*CandidateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CandidateSelect) Aggregate(fns ...AggregateFunc) *CandidateSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CandidateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CandidateQuery, *CandidateSelect](ctx, _s.CandidateQuery, _s, _s.inters, v)
}

func (_s *CandidateSelect) sqlScan(ctx context.Context, root *CandidateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
