// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidatesnapshot"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/socialsnapshot"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/tradedecision"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/verdict"
)

// CandidateCreate is the builder for creating a Candidate entity.
type CandidateCreate struct {
	config
	mutation *CandidateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNetwork sets the "network" field.
func (_c *CandidateCreate) SetNetwork(v string) *CandidateCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetMintAddress sets the "mint_address" field.
func (_c *CandidateCreate) SetMintAddress(v string) *CandidateCreate {
	_c.mutation.SetMintAddress(v)
	return _c
}

// SetPoolAddress sets the "pool_address" field.
func (_c *CandidateCreate) SetPoolAddress(v string) *CandidateCreate {
	_c.mutation.SetPoolAddress(v)
	return _c
}

// SetDiscoveredAt sets the "discovered_at" field.
func (_c *CandidateCreate) SetDiscoveredAt(v time.Time) *CandidateCreate {
	_c.mutation.SetDiscoveredAt(v)
	return _c
}

// SetNillableDiscoveredAt sets the "discovered_at" field if the given value is not nil.
func (_c *CandidateCreate) SetNillableDiscoveredAt(v *time.Time) *CandidateCreate {
	if v != nil {
		_c.SetDiscoveredAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CandidateCreate) SetCreatedAt(v time.Time) *CandidateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CandidateCreate) SetNillableCreatedAt(v *time.Time) *CandidateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CandidateCreate) SetUpdatedAt(v time.Time) *CandidateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CandidateCreate) SetNillableUpdatedAt(v *time.Time) *CandidateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddSnapshotIDs adds the "snapshots" edge to the CandidateSnapshot entity by IDs.
func (_c *CandidateCreate) AddSnapshotIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddSnapshotIDs(ids...)
	return _c
}

// AddSnapshots adds the "snapshots" edges to the CandidateSnapshot entity.
func (_c *CandidateCreate) AddSnapshots(v ...*CandidateSnapshot) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSnapshotIDs(ids...)
}

// AddSocialSnapshotIDs adds the "social_snapshots" edge to the SocialSnapshot entity by IDs.
func (_c *CandidateCreate) AddSocialSnapshotIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddSocialSnapshotIDs(ids...)
	return _c
}

// AddSocialSnapshots adds the "social_snapshots" edges to the SocialSnapshot entity.
func (_c *CandidateCreate) AddSocialSnapshots(v ...*SocialSnapshot) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSocialSnapshotIDs(ids...)
}

// AddVerdictIDs adds the "verdicts" edge to the Verdict entity by IDs.
func (_c *CandidateCreate) AddVerdictIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddVerdictIDs(ids...)
	return _c
}

// AddVerdicts adds the "verdicts" edges to the Verdict entity.
func (_c *CandidateCreate) AddVerdicts(v ...*Verdict) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVerdictIDs(ids...)
}

// AddDecisionIDs adds the "decisions" edge to the TradeDecision entity by IDs.
func (_c *CandidateCreate) AddDecisionIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddDecisionIDs(ids...)
	return _c
}

// AddDecisions adds the "decisions" edges to the TradeDecision entity.
func (_c *CandidateCreate) AddDecisions(v ...*TradeDecision) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDecisionIDs(ids...)
}

// AddPositionIDs adds the "positions" edge to the PaperPosition entity by IDs.
func (_c *CandidateCreate) AddPositionIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddPositionIDs(ids...)
	return _c
}

// AddPositions adds the "positions" edges to the PaperPosition entity.
func (_c *CandidateCreate) AddPositions(v ...*PaperPosition) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPositionIDs(ids...)
}

// Mutation returns the CandidateMutation object of the builder.
func (_c *CandidateCreate) Mutation() *CandidateMutation {
	return _c.mutation
}

// Save creates the Candidate in the database.
func (_c *CandidateCreate) Save(ctx context.Context) (*Candidate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CandidateCreate) SaveX(ctx context.Context) *Candidate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CandidateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CandidateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CandidateCreate) defaults() {
	if _, ok := _c.mutation.DiscoveredAt(); !ok {
		v := candidate.DefaultDiscoveredAt()
		_c.mutation.SetDiscoveredAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := candidate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := candidate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CandidateCreate) check() error {
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "Candidate.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := candidate.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "Candidate.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MintAddress(); !ok {
		return &ValidationError{Name: "mint_address", err: errors.New(`ent: missing required field "Candidate.mint_address"`)}
	}
	if v, ok := _c.mutation.MintAddress(); ok {
		if err := candidate.MintAddressValidator(v); err != nil {
			return &ValidationError{Name: "mint_address", err: fmt.Errorf(`ent: validator failed for field "Candidate.mint_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PoolAddress(); !ok {
		return &ValidationError{Name: "pool_address", err: errors.New(`ent: missing required field "Candidate.pool_address"`)}
	}
	if v, ok := _c.mutation.PoolAddress(); ok {
		if err := candidate.PoolAddressValidator(v); err != nil {
			return &ValidationError{Name: "pool_address", err: fmt.Errorf(`ent: validator failed for field "Candidate.pool_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DiscoveredAt(); !ok {
		return &ValidationError{Name: "discovered_at", err: errors.New(`ent: missing required field "Candidate.discovered_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Candidate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Candidate.updated_at"`)}
	}
	return nil
}

func (_c *CandidateCreate) sqlSave(ctx context.Context) (*Candidate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CandidateCreate) createSpec() (*Candidate, *sqlgraph.CreateSpec) {
	var (
		_node = &Candidate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(candidate.Table, sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(candidate.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.MintAddress(); ok {
		_spec.SetField(candidate.FieldMintAddress, field.TypeString, value)
		_node.MintAddress = value
	}
	if value, ok := _c.mutation.PoolAddress(); ok {
		_spec.SetField(candidate.FieldPoolAddress, field.TypeString, value)
		_node.PoolAddress = value
	}
	if value, ok := _c.mutation.DiscoveredAt(); ok {
		_spec.SetField(candidate.FieldDiscoveredAt, field.TypeTime, value)
		_node.DiscoveredAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(candidate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(candidate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.SnapshotsTable,
			Columns: []string{candidate.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidatesnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SocialSnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.SocialSnapshotsTable,
			Columns: []string{candidate.SocialSnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VerdictsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.VerdictsTable,
			Columns: []string{candidate.VerdictsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verdict.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DecisionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.DecisionsTable,
			Columns: []string{candidate.DecisionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.PositionsTable,
			Columns: []string{candidate.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Candidate.Create().
//		SetNetwork(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CandidateUpsert) {
//			SetNetwork(v+v).
//		}).
//		Exec(ctx)
func (_c *CandidateCreate) OnConflict(opts ...sql.ConflictOption) *CandidateUpsertOne {
	_c.conflict = opts
	return &CandidateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Candidate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CandidateCreate) OnConflictColumns(columns ...string) *CandidateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CandidateUpsertOne{
		create: _c,
	}
}

type (
	// CandidateUpsertOne is the builder for "upsert"-ing
	//  one Candidate node.
	CandidateUpsertOne struct {
		create *CandidateCreate
	}

	// CandidateUpsert is the "OnConflict" setter.
	CandidateUpsert struct {
		*sql.UpdateSet
	}
)

// SetNetwork sets the "network" field.
func (u *CandidateUpsert) SetNetwork(v string) *CandidateUpsert {
	u.Set(candidate.FieldNetwork, v)
	return u
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *CandidateUpsert) UpdateNetwork() *CandidateUpsert {
	u.SetExcluded(candidate.FieldNetwork)
	return u
}

// SetMintAddress sets the "mint_address" field.
func (u *CandidateUpsert) SetMintAddress(v string) *CandidateUpsert {
	u.Set(candidate.FieldMintAddress, v)
	return u
}

// UpdateMintAddress sets the "mint_address" field to the value that was provided on create.
func (u *CandidateUpsert) UpdateMintAddress() *CandidateUpsert {
	u.SetExcluded(candidate.FieldMintAddress)
	return u
}

// SetPoolAddress sets the "pool_address" field.
func (u *CandidateUpsert) SetPoolAddress(v string) *CandidateUpsert {
	u.Set(candidate.FieldPoolAddress, v)
	return u
}

// UpdatePoolAddress sets the "pool_address" field to the value that was provided on create.
func (u *CandidateUpsert) UpdatePoolAddress() *CandidateUpsert {
	u.SetExcluded(candidate.FieldPoolAddress)
	return u
}

// SetDiscoveredAt sets the "discovered_at" field.
func (u *CandidateUpsert) SetDiscoveredAt(v time.Time) *CandidateUpsert {
	u.Set(candidate.FieldDiscoveredAt, v)
	return u
}

// UpdateDiscoveredAt sets the "discovered_at" field to the value that was provided on create.
func (u *CandidateUpsert) UpdateDiscoveredAt() *CandidateUpsert {
	u.SetExcluded(candidate.FieldDiscoveredAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CandidateUpsert) SetUpdatedAt(v time.Time) *CandidateUpsert {
	u.Set(candidate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CandidateUpsert) UpdateUpdatedAt() *CandidateUpsert {
	u.SetExcluded(candidate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Candidate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CandidateUpsertOne) UpdateNewValues() *CandidateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(candidate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Candidate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CandidateUpsertOne) Ignore() *CandidateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CandidateUpsertOne) DoNothing() *CandidateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CandidateCreate.OnConflict
// documentation for more info.
func (u *CandidateUpsertOne) Update(set func(*CandidateUpsert)) *CandidateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CandidateUpsert{UpdateSet: update})
	}))
	return u
}

// SetNetwork sets the "network" field.
func (u *CandidateUpsertOne) SetNetwork(v string) *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *CandidateUpsertOne) UpdateNetwork() *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdateNetwork()
	})
}

// SetMintAddress sets the "mint_address" field.
func (u *CandidateUpsertOne) SetMintAddress(v string) *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.SetMintAddress(v)
	})
}

// UpdateMintAddress sets the "mint_address" field to the value that was provided on create.
func (u *CandidateUpsertOne) UpdateMintAddress() *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdateMintAddress()
	})
}

// SetPoolAddress sets the "pool_address" field.
func (u *CandidateUpsertOne) SetPoolAddress(v string) *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.SetPoolAddress(v)
	})
}

// UpdatePoolAddress sets the "pool_address" field to the value that was provided on create.
func (u *CandidateUpsertOne) UpdatePoolAddress() *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdatePoolAddress()
	})
}

// SetDiscoveredAt sets the "discovered_at" field.
func (u *CandidateUpsertOne) SetDiscoveredAt(v time.Time) *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.SetDiscoveredAt(v)
	})
}

// UpdateDiscoveredAt sets the "discovered_at" field to the value that was provided on create.
func (u *CandidateUpsertOne) UpdateDiscoveredAt() *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdateDiscoveredAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CandidateUpsertOne) SetUpdatedAt(v time.Time) *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CandidateUpsertOne) UpdateUpdatedAt() *CandidateUpsertOne {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CandidateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CandidateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CandidateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CandidateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CandidateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CandidateCreateBulk is the builder for creating many Candidate entities in bulk.
type CandidateCreateBulk struct {
	config
	err      error
	builders []*CandidateCreate
	conflict []sql.ConflictOption
}

// Save creates the Candidate entities in the database.
func (_c *CandidateCreateBulk) Save(ctx context.Context) ([]*Candidate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Candidate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CandidateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CandidateCreateBulk) SaveX(ctx context.Context) []*Candidate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CandidateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CandidateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Candidate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CandidateUpsert) {
//			SetNetwork(v+v).
//		}).
//		Exec(ctx)
func (_c *CandidateCreateBulk) OnConflict(opts ...sql.ConflictOption) *CandidateUpsertBulk {
	_c.conflict = opts
	return &CandidateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Candidate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CandidateCreateBulk) OnConflictColumns(columns ...string) *CandidateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CandidateUpsertBulk{
		create: _c,
	}
}

// CandidateUpsertBulk is the builder for "upsert"-ing
// a bulk of Candidate nodes.
type CandidateUpsertBulk struct {
	create *CandidateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Candidate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CandidateUpsertBulk) UpdateNewValues() *CandidateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(candidate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Candidate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CandidateUpsertBulk) Ignore() *CandidateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CandidateUpsertBulk) DoNothing() *CandidateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CandidateCreateBulk.OnConflict
// documentation for more info.
func (u *CandidateUpsertBulk) Update(set func(*CandidateUpsert)) *CandidateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CandidateUpsert{UpdateSet: update})
	}))
	return u
}

// SetNetwork sets the "network" field.
func (u *CandidateUpsertBulk) SetNetwork(v string) *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *CandidateUpsertBulk) UpdateNetwork() *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdateNetwork()
	})
}

// SetMintAddress sets the "mint_address" field.
func (u *CandidateUpsertBulk) SetMintAddress(v string) *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.SetMintAddress(v)
	})
}

// UpdateMintAddress sets the "mint_address" field to the value that was provided on create.
func (u *CandidateUpsertBulk) UpdateMintAddress() *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdateMintAddress()
	})
}

// SetPoolAddress sets the "pool_address" field.
func (u *CandidateUpsertBulk) SetPoolAddress(v string) *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.SetPoolAddress(v)
	})
}

// UpdatePoolAddress sets the "pool_address" field to the value that was provided on create.
func (u *CandidateUpsertBulk) UpdatePoolAddress() *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdatePoolAddress()
	})
}

// SetDiscoveredAt sets the "discovered_at" field.
func (u *CandidateUpsertBulk) SetDiscoveredAt(v time.Time) *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.SetDiscoveredAt(v)
	})
}

// UpdateDiscoveredAt sets the "discovered_at" field to the value that was provided on create.
func (u *CandidateUpsertBulk) UpdateDiscoveredAt() *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdateDiscoveredAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CandidateUpsertBulk) SetUpdatedAt(v time.Time) *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CandidateUpsertBulk) UpdateUpdatedAt() *CandidateUpsertBulk {
	return u.Update(func(s *CandidateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CandidateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CandidateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CandidateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CandidateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
