// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidatesnapshot"
)

// CandidateSnapshot is the model entity for the CandidateSnapshot schema.
type CandidateSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MarketEvidence holds the value of the "market_evidence" field.
	MarketEvidence map[string]interface{} `json:"market_evidence,omitempty"`
	// ObservedAt holds the value of the "observed_at" field.
	ObservedAt time.Time `json:"observed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CandidateSnapshotQuery when eager-loading is set.
	Edges               CandidateSnapshotEdges `json:"edges"`
	candidate_snapshots *int
	selectValues        sql.SelectValues
}

// CandidateSnapshotEdges holds the relations/edges for other nodes in the graph.
type CandidateSnapshotEdges struct {
	// Candidate holds the value of the candidate edge.
	Candidate *Candidate `json:"candidate,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CandidateOrErr returns the Candidate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CandidateSnapshotEdges) CandidateOrErr() (*Candidate, error) {
	if e.Candidate != nil {
		return e.Candidate, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: candidate.Label}
	}
	return nil, &NotLoadedError{edge: "candidate"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CandidateSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case candidatesnapshot.FieldMarketEvidence:
			values[i] = new([]byte)
		case candidatesnapshot.FieldID:
			values[i] = new(sql.NullInt64)
		case candidatesnapshot.FieldObservedAt, candidatesnapshot.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case candidatesnapshot.ForeignKeys[0]: // candidate_snapshots
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CandidateSnapshot fields.
func (_m *CandidateSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case candidatesnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case candidatesnapshot.FieldMarketEvidence:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field market_evidence", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MarketEvidence); err != nil {
					return fmt.Errorf("unmarshal field market_evidence: %w", err)
				}
			}
		case candidatesnapshot.FieldObservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field observed_at", values[i])
			} else if value.Valid {
				_m.ObservedAt = value.Time
			}
		case candidatesnapshot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case candidatesnapshot.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field candidate_snapshots", value)
			} else if value.Valid {
				_m.candidate_snapshots = new(int)
				*_m.candidate_snapshots = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CandidateSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *CandidateSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCandidate queries the "candidate" edge of the CandidateSnapshot entity.
func (_m *CandidateSnapshot) QueryCandidate() *CandidateQuery {
	return NewCandidateSnapshotClient(_m.config).QueryCandidate(_m)
}

// Update returns a builder for updating this CandidateSnapshot.
// Note that you need to call CandidateSnapshot.Unwrap() before calling this method if this CandidateSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CandidateSnapshot) Update() *CandidateSnapshotUpdateOne {
	return NewCandidateSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CandidateSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CandidateSnapshot) Unwrap() *CandidateSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CandidateSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CandidateSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("CandidateSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("market_evidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.MarketEvidence))
	builder.WriteString(", ")
	builder.WriteString("observed_at=")
	builder.WriteString(_m.ObservedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CandidateSnapshots is a parsable slice of CandidateSnapshot.
type CandidateSnapshots []*CandidateSnapshot
