// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/dailyresult"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
)

// DailyResultUpdate is the builder for updating DailyResult entities.
type DailyResultUpdate struct {
	config
	hooks    []Hook
	mutation *DailyResultMutation
}

// Where appends a list predicates to the DailyResultUpdate builder.
func (_u *DailyResultUpdate) Where(ps ...predicate.DailyResult) *DailyResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUtcDate sets the "utc_date" field.
func (_u *DailyResultUpdate) SetUtcDate(v time.Time) *DailyResultUpdate {
	_u.mutation.SetUtcDate(v)
	return _u
}

// SetNillableUtcDate sets the "utc_date" field if the given value is not nil.
func (_u *DailyResultUpdate) SetNillableUtcDate(v *time.Time) *DailyResultUpdate {
	if v != nil {
		_u.SetUtcDate(*v)
	}
	return _u
}

// SetStrategyVersion sets the "strategy_version" field.
func (_u *DailyResultUpdate) SetStrategyVersion(v string) *DailyResultUpdate {
	_u.mutation.SetStrategyVersion(v)
	return _u
}

// SetNillableStrategyVersion sets the "strategy_version" field if the given value is not nil.
func (_u *DailyResultUpdate) SetNillableStrategyVersion(v *string) *DailyResultUpdate {
	if v != nil {
		_u.SetStrategyVersion(*v)
	}
	return _u
}

// SetDailyAdmittedCount sets the "daily_admitted_count" field.
func (_u *DailyResultUpdate) SetDailyAdmittedCount(v int) *DailyResultUpdate {
	_u.mutation.ResetDailyAdmittedCount()
	_u.mutation.SetDailyAdmittedCount(v)
	return _u
}

// SetNillableDailyAdmittedCount sets the "daily_admitted_count" field if the given value is not nil.
func (_u *DailyResultUpdate) SetNillableDailyAdmittedCount(v *int) *DailyResultUpdate {
	if v != nil {
		_u.SetDailyAdmittedCount(*v)
	}
	return _u
}

// AddDailyAdmittedCount adds value to the "daily_admitted_count" field.
func (_u *DailyResultUpdate) AddDailyAdmittedCount(v int) *DailyResultUpdate {
	_u.mutation.AddDailyAdmittedCount(v)
	return _u
}

// SetRealizedPnlMicros sets the "realized_pnl_micros" field.
func (_u *DailyResultUpdate) SetRealizedPnlMicros(v int64) *DailyResultUpdate {
	_u.mutation.ResetRealizedPnlMicros()
	_u.mutation.SetRealizedPnlMicros(v)
	return _u
}

// SetNillableRealizedPnlMicros sets the "realized_pnl_micros" field if the given value is not nil.
func (_u *DailyResultUpdate) SetNillableRealizedPnlMicros(v *int64) *DailyResultUpdate {
	if v != nil {
		_u.SetRealizedPnlMicros(*v)
	}
	return _u
}

// AddRealizedPnlMicros adds value to the "realized_pnl_micros" field.
func (_u *DailyResultUpdate) AddRealizedPnlMicros(v int64) *DailyResultUpdate {
	_u.mutation.AddRealizedPnlMicros(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DailyResultUpdate) SetUpdatedAt(v time.Time) *DailyResultUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DailyResultMutation object of the builder.
func (_u *DailyResultUpdate) Mutation() *DailyResultMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyResultUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyResultUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dailyresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyResultUpdate) check() error {
	if v, ok := _u.mutation.StrategyVersion(); ok {
		if err := dailyresult.StrategyVersionValidator(v); err != nil {
			return &ValidationError{Name: "strategy_version", err: fmt.Errorf(`ent: validator failed for field "DailyResult.strategy_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DailyAdmittedCount(); ok {
		if err := dailyresult.DailyAdmittedCountValidator(v); err != nil {
			return &ValidationError{Name: "daily_admitted_count", err: fmt.Errorf(`ent: validator failed for field "DailyResult.daily_admitted_count": %w`, err)}
		}
	}
	return nil
}

func (_u *DailyResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailyresult.Table, dailyresult.Columns, sqlgraph.NewFieldSpec(dailyresult.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UtcDate(); ok {
		_spec.SetField(dailyresult.FieldUtcDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StrategyVersion(); ok {
		_spec.SetField(dailyresult.FieldStrategyVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyAdmittedCount(); ok {
		_spec.SetField(dailyresult.FieldDailyAdmittedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDailyAdmittedCount(); ok {
		_spec.AddField(dailyresult.FieldDailyAdmittedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealizedPnlMicros(); ok {
		_spec.SetField(dailyresult.FieldRealizedPnlMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRealizedPnlMicros(); ok {
		_spec.AddField(dailyresult.FieldRealizedPnlMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dailyresult.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailyresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyResultUpdateOne is the builder for updating a single DailyResult entity.
type DailyResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyResultMutation
}

// SetUtcDate sets the "utc_date" field.
func (_u *DailyResultUpdateOne) SetUtcDate(v time.Time) *DailyResultUpdateOne {
	_u.mutation.SetUtcDate(v)
	return _u
}

// SetNillableUtcDate sets the "utc_date" field if the given value is not nil.
func (_u *DailyResultUpdateOne) SetNillableUtcDate(v *time.Time) *DailyResultUpdateOne {
	if v != nil {
		_u.SetUtcDate(*v)
	}
	return _u
}

// SetStrategyVersion sets the "strategy_version" field.
func (_u *DailyResultUpdateOne) SetStrategyVersion(v string) *DailyResultUpdateOne {
	_u.mutation.SetStrategyVersion(v)
	return _u
}

// SetNillableStrategyVersion sets the "strategy_version" field if the given value is not nil.
func (_u *DailyResultUpdateOne) SetNillableStrategyVersion(v *string) *DailyResultUpdateOne {
	if v != nil {
		_u.SetStrategyVersion(*v)
	}
	return _u
}

// SetDailyAdmittedCount sets the "daily_admitted_count" field.
func (_u *DailyResultUpdateOne) SetDailyAdmittedCount(v int) *DailyResultUpdateOne {
	_u.mutation.ResetDailyAdmittedCount()
	_u.mutation.SetDailyAdmittedCount(v)
	return _u
}

// SetNillableDailyAdmittedCount sets the "daily_admitted_count" field if the given value is not nil.
func (_u *DailyResultUpdateOne) SetNillableDailyAdmittedCount(v *int) *DailyResultUpdateOne {
	if v != nil {
		_u.SetDailyAdmittedCount(*v)
	}
	return _u
}

// AddDailyAdmittedCount adds value to the "daily_admitted_count" field.
func (_u *DailyResultUpdateOne) AddDailyAdmittedCount(v int) *DailyResultUpdateOne {
	_u.mutation.AddDailyAdmittedCount(v)
	return _u
}

// SetRealizedPnlMicros sets the "realized_pnl_micros" field.
func (_u *DailyResultUpdateOne) SetRealizedPnlMicros(v int64) *DailyResultUpdateOne {
	_u.mutation.ResetRealizedPnlMicros()
	_u.mutation.SetRealizedPnlMicros(v)
	return _u
}

// SetNillableRealizedPnlMicros sets the "realized_pnl_micros" field if the given value is not nil.
func (_u *DailyResultUpdateOne) SetNillableRealizedPnlMicros(v *int64) *DailyResultUpdateOne {
	if v != nil {
		_u.SetRealizedPnlMicros(*v)
	}
	return _u
}

// AddRealizedPnlMicros adds value to the "realized_pnl_micros" field.
func (_u *DailyResultUpdateOne) AddRealizedPnlMicros(v int64) *DailyResultUpdateOne {
	_u.mutation.AddRealizedPnlMicros(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DailyResultUpdateOne) SetUpdatedAt(v time.Time) *DailyResultUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DailyResultMutation object of the builder.
func (_u *DailyResultUpdateOne) Mutation() *DailyResultMutation {
	return _u.mutation
}

// Where appends a list predicates to the DailyResultUpdate builder.
func (_u *DailyResultUpdateOne) Where(ps ...predicate.DailyResult) *DailyResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyResultUpdateOne) Select(field string, fields ...string) *DailyResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyResult entity.
func (_u *DailyResultUpdateOne) Save(ctx context.Context) (*DailyResult, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyResultUpdateOne) SaveX(ctx context.Context) *DailyResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyResultUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dailyresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyResultUpdateOne) check() error {
	if v, ok := _u.mutation.StrategyVersion(); ok {
		if err := dailyresult.StrategyVersionValidator(v); err != nil {
			return &ValidationError{Name: "strategy_version", err: fmt.Errorf(`ent: validator failed for field "DailyResult.strategy_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DailyAdmittedCount(); ok {
		if err := dailyresult.DailyAdmittedCountValidator(v); err != nil {
			return &ValidationError{Name: "daily_admitted_count", err: fmt.Errorf(`ent: validator failed for field "DailyResult.daily_admitted_count": %w`, err)}
		}
	}
	return nil
}

func (_u *DailyResultUpdateOne) sqlSave(ctx context.Context) (_node *DailyResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailyresult.Table, dailyresult.Columns, sqlgraph.NewFieldSpec(dailyresult.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailyresult.FieldID)
		for _, f := range fields {
			if !dailyresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailyresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UtcDate(); ok {
		_spec.SetField(dailyresult.FieldUtcDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StrategyVersion(); ok {
		_spec.SetField(dailyresult.FieldStrategyVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyAdmittedCount(); ok {
		_spec.SetField(dailyresult.FieldDailyAdmittedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDailyAdmittedCount(); ok {
		_spec.AddField(dailyresult.FieldDailyAdmittedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealizedPnlMicros(); ok {
		_spec.SetField(dailyresult.FieldRealizedPnlMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRealizedPnlMicros(); ok {
		_spec.AddField(dailyresult.FieldRealizedPnlMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dailyresult.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DailyResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailyresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
