// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/positionevent"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/positionmark"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/tradedecision"
)

// PaperPositionUpdate is the builder for updating PaperPosition entities.
type PaperPositionUpdate struct {
	config
	hooks    []Hook
	mutation *PaperPositionMutation
}

// Where appends a list predicates to the PaperPositionUpdate builder.
func (_u *PaperPositionUpdate) Where(ps ...predicate.PaperPosition) *PaperPositionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *PaperPositionUpdate) SetState(v paperposition.State) *PaperPositionUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableState(v *paperposition.State) *PaperPositionUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetNotionalMicros sets the "notional_micros" field.
func (_u *PaperPositionUpdate) SetNotionalMicros(v int64) *PaperPositionUpdate {
	_u.mutation.ResetNotionalMicros()
	_u.mutation.SetNotionalMicros(v)
	return _u
}

// SetNillableNotionalMicros sets the "notional_micros" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableNotionalMicros(v *int64) *PaperPositionUpdate {
	if v != nil {
		_u.SetNotionalMicros(*v)
	}
	return _u
}

// AddNotionalMicros adds value to the "notional_micros" field.
func (_u *PaperPositionUpdate) AddNotionalMicros(v int64) *PaperPositionUpdate {
	_u.mutation.AddNotionalMicros(v)
	return _u
}

// SetStrategyVersion sets the "strategy_version" field.
func (_u *PaperPositionUpdate) SetStrategyVersion(v string) *PaperPositionUpdate {
	_u.mutation.SetStrategyVersion(v)
	return _u
}

// SetNillableStrategyVersion sets the "strategy_version" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableStrategyVersion(v *string) *PaperPositionUpdate {
	if v != nil {
		_u.SetStrategyVersion(*v)
	}
	return _u
}

// SetNoRouteCount sets the "no_route_count" field.
func (_u *PaperPositionUpdate) SetNoRouteCount(v int) *PaperPositionUpdate {
	_u.mutation.ResetNoRouteCount()
	_u.mutation.SetNoRouteCount(v)
	return _u
}

// SetNillableNoRouteCount sets the "no_route_count" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableNoRouteCount(v *int) *PaperPositionUpdate {
	if v != nil {
		_u.SetNoRouteCount(*v)
	}
	return _u
}

// AddNoRouteCount adds value to the "no_route_count" field.
func (_u *PaperPositionUpdate) AddNoRouteCount(v int) *PaperPositionUpdate {
	_u.mutation.AddNoRouteCount(v)
	return _u
}

// SetQuoteMint sets the "quote_mint" field.
func (_u *PaperPositionUpdate) SetQuoteMint(v string) *PaperPositionUpdate {
	_u.mutation.SetQuoteMint(v)
	return _u
}

// SetNillableQuoteMint sets the "quote_mint" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableQuoteMint(v *string) *PaperPositionUpdate {
	if v != nil {
		_u.SetQuoteMint(*v)
	}
	return _u
}

// ClearQuoteMint clears the value of the "quote_mint" field.
func (_u *PaperPositionUpdate) ClearQuoteMint() *PaperPositionUpdate {
	_u.mutation.ClearQuoteMint()
	return _u
}

// SetMintAddress sets the "mint_address" field.
func (_u *PaperPositionUpdate) SetMintAddress(v string) *PaperPositionUpdate {
	_u.mutation.SetMintAddress(v)
	return _u
}

// SetNillableMintAddress sets the "mint_address" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableMintAddress(v *string) *PaperPositionUpdate {
	if v != nil {
		_u.SetMintAddress(*v)
	}
	return _u
}

// ClearMintAddress clears the value of the "mint_address" field.
func (_u *PaperPositionUpdate) ClearMintAddress() *PaperPositionUpdate {
	_u.mutation.ClearMintAddress()
	return _u
}

// SetEntryPrice sets the "entry_price" field.
func (_u *PaperPositionUpdate) SetEntryPrice(v string) *PaperPositionUpdate {
	_u.mutation.SetEntryPrice(v)
	return _u
}

// SetNillableEntryPrice sets the "entry_price" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableEntryPrice(v *string) *PaperPositionUpdate {
	if v != nil {
		_u.SetEntryPrice(*v)
	}
	return _u
}

// ClearEntryPrice clears the value of the "entry_price" field.
func (_u *PaperPositionUpdate) ClearEntryPrice() *PaperPositionUpdate {
	_u.mutation.ClearEntryPrice()
	return _u
}

// SetEntryInputAmount sets the "entry_input_amount" field.
func (_u *PaperPositionUpdate) SetEntryInputAmount(v string) *PaperPositionUpdate {
	_u.mutation.SetEntryInputAmount(v)
	return _u
}

// SetNillableEntryInputAmount sets the "entry_input_amount" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableEntryInputAmount(v *string) *PaperPositionUpdate {
	if v != nil {
		_u.SetEntryInputAmount(*v)
	}
	return _u
}

// ClearEntryInputAmount clears the value of the "entry_input_amount" field.
func (_u *PaperPositionUpdate) ClearEntryInputAmount() *PaperPositionUpdate {
	_u.mutation.ClearEntryInputAmount()
	return _u
}

// SetEntryNetworkFeeMicros sets the "entry_network_fee_micros" field.
func (_u *PaperPositionUpdate) SetEntryNetworkFeeMicros(v int64) *PaperPositionUpdate {
	_u.mutation.ResetEntryNetworkFeeMicros()
	_u.mutation.SetEntryNetworkFeeMicros(v)
	return _u
}

// SetNillableEntryNetworkFeeMicros sets the "entry_network_fee_micros" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableEntryNetworkFeeMicros(v *int64) *PaperPositionUpdate {
	if v != nil {
		_u.SetEntryNetworkFeeMicros(*v)
	}
	return _u
}

// AddEntryNetworkFeeMicros adds value to the "entry_network_fee_micros" field.
func (_u *PaperPositionUpdate) AddEntryNetworkFeeMicros(v int64) *PaperPositionUpdate {
	_u.mutation.AddEntryNetworkFeeMicros(v)
	return _u
}

// ClearEntryNetworkFeeMicros clears the value of the "entry_network_fee_micros" field.
func (_u *PaperPositionUpdate) ClearEntryNetworkFeeMicros() *PaperPositionUpdate {
	_u.mutation.ClearEntryNetworkFeeMicros()
	return _u
}

// SetEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field.
func (_u *PaperPositionUpdate) SetEntryPriorityFeeMicros(v int64) *PaperPositionUpdate {
	_u.mutation.ResetEntryPriorityFeeMicros()
	_u.mutation.SetEntryPriorityFeeMicros(v)
	return _u
}

// SetNillableEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableEntryPriorityFeeMicros(v *int64) *PaperPositionUpdate {
	if v != nil {
		_u.SetEntryPriorityFeeMicros(*v)
	}
	return _u
}

// AddEntryPriorityFeeMicros adds value to the "entry_priority_fee_micros" field.
func (_u *PaperPositionUpdate) AddEntryPriorityFeeMicros(v int64) *PaperPositionUpdate {
	_u.mutation.AddEntryPriorityFeeMicros(v)
	return _u
}

// ClearEntryPriorityFeeMicros clears the value of the "entry_priority_fee_micros" field.
func (_u *PaperPositionUpdate) ClearEntryPriorityFeeMicros() *PaperPositionUpdate {
	_u.mutation.ClearEntryPriorityFeeMicros()
	return _u
}

// SetTokenQuantity sets the "token_quantity" field.
func (_u *PaperPositionUpdate) SetTokenQuantity(v string) *PaperPositionUpdate {
	_u.mutation.SetTokenQuantity(v)
	return _u
}

// SetNillableTokenQuantity sets the "token_quantity" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableTokenQuantity(v *string) *PaperPositionUpdate {
	if v != nil {
		_u.SetTokenQuantity(*v)
	}
	return _u
}

// ClearTokenQuantity clears the value of the "token_quantity" field.
func (_u *PaperPositionUpdate) ClearTokenQuantity() *PaperPositionUpdate {
	_u.mutation.ClearTokenQuantity()
	return _u
}

// SetOpenedAt sets the "opened_at" field.
func (_u *PaperPositionUpdate) SetOpenedAt(v time.Time) *PaperPositionUpdate {
	_u.mutation.SetOpenedAt(v)
	return _u
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableOpenedAt(v *time.Time) *PaperPositionUpdate {
	if v != nil {
		_u.SetOpenedAt(*v)
	}
	return _u
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (_u *PaperPositionUpdate) ClearOpenedAt() *PaperPositionUpdate {
	_u.mutation.ClearOpenedAt()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *PaperPositionUpdate) SetClosedAt(v time.Time) *PaperPositionUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *PaperPositionUpdate) SetNillableClosedAt(v *time.Time) *PaperPositionUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *PaperPositionUpdate) ClearClosedAt() *PaperPositionUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaperPositionUpdate) SetUpdatedAt(v time.Time) *PaperPositionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_u *PaperPositionUpdate) SetCandidateID(id int) *PaperPositionUpdate {
	_u.mutation.SetCandidateID(id)
	return _u
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_u *PaperPositionUpdate) SetCandidate(v *Candidate) *PaperPositionUpdate {
	return _u.SetCandidateID(v.ID)
}

// SetDecisionID sets the "decision" edge to the TradeDecision entity by ID.
func (_u *PaperPositionUpdate) SetDecisionID(id int) *PaperPositionUpdate {
	_u.mutation.SetDecisionID(id)
	return _u
}

// SetDecision sets the "decision" edge to the TradeDecision entity.
func (_u *PaperPositionUpdate) SetDecision(v *TradeDecision) *PaperPositionUpdate {
	return _u.SetDecisionID(v.ID)
}

// AddMarkIDs adds the "marks" edge to the PositionMark entity by IDs.
func (_u *PaperPositionUpdate) AddMarkIDs(ids ...int) *PaperPositionUpdate {
	_u.mutation.AddMarkIDs(ids...)
	return _u
}

// AddMarks adds the "marks" edges to the PositionMark entity.
func (_u *PaperPositionUpdate) AddMarks(v ...*PositionMark) *PaperPositionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMarkIDs(ids...)
}

// AddEventIDs adds the "events" edge to the PositionEvent entity by IDs.
func (_u *PaperPositionUpdate) AddEventIDs(ids ...int) *PaperPositionUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the PositionEvent entity.
func (_u *PaperPositionUpdate) AddEvents(v ...*PositionEvent) *PaperPositionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the PaperPositionMutation object of the builder.
func (_u *PaperPositionUpdate) Mutation() *PaperPositionMutation {
	return _u.mutation
}

// ClearCandidate clears the "candidate" edge to the Candidate entity.
func (_u *PaperPositionUpdate) ClearCandidate() *PaperPositionUpdate {
	_u.mutation.ClearCandidate()
	return _u
}

// ClearDecision clears the "decision" edge to the TradeDecision entity.
func (_u *PaperPositionUpdate) ClearDecision() *PaperPositionUpdate {
	_u.mutation.ClearDecision()
	return _u
}

// ClearMarks clears all "marks" edges to the PositionMark entity.
func (_u *PaperPositionUpdate) ClearMarks() *PaperPositionUpdate {
	_u.mutation.ClearMarks()
	return _u
}

// RemoveMarkIDs removes the "marks" edge to PositionMark entities by IDs.
func (_u *PaperPositionUpdate) RemoveMarkIDs(ids ...int) *PaperPositionUpdate {
	_u.mutation.RemoveMarkIDs(ids...)
	return _u
}

// RemoveMarks removes "marks" edges to PositionMark entities.
func (_u *PaperPositionUpdate) RemoveMarks(v ...*PositionMark) *PaperPositionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMarkIDs(ids...)
}

// ClearEvents clears all "events" edges to the PositionEvent entity.
func (_u *PaperPositionUpdate) ClearEvents() *PaperPositionUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to PositionEvent entities by IDs.
func (_u *PaperPositionUpdate) RemoveEventIDs(ids ...int) *PaperPositionUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to PositionEvent entities.
func (_u *PaperPositionUpdate) RemoveEvents(v ...*PositionEvent) *PaperPositionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaperPositionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaperPositionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaperPositionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaperPositionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaperPositionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paperposition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaperPositionUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := paperposition.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NotionalMicros(); ok {
		if err := paperposition.NotionalMicrosValidator(v); err != nil {
			return &ValidationError{Name: "notional_micros", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.notional_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyVersion(); ok {
		if err := paperposition.StrategyVersionValidator(v); err != nil {
			return &ValidationError{Name: "strategy_version", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.strategy_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NoRouteCount(); ok {
		if err := paperposition.NoRouteCountValidator(v); err != nil {
			return &ValidationError{Name: "no_route_count", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.no_route_count": %w`, err)}
		}
	}
	if _u.mutation.CandidateCleared() && len(_u.mutation.CandidateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaperPosition.candidate"`)
	}
	if _u.mutation.DecisionCleared() && len(_u.mutation.DecisionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaperPosition.decision"`)
	}
	return nil
}

func (_u *PaperPositionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paperposition.Table, paperposition.Columns, sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(paperposition.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NotionalMicros(); ok {
		_spec.SetField(paperposition.FieldNotionalMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNotionalMicros(); ok {
		_spec.AddField(paperposition.FieldNotionalMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StrategyVersion(); ok {
		_spec.SetField(paperposition.FieldStrategyVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.NoRouteCount(); ok {
		_spec.SetField(paperposition.FieldNoRouteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNoRouteCount(); ok {
		_spec.AddField(paperposition.FieldNoRouteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuoteMint(); ok {
		_spec.SetField(paperposition.FieldQuoteMint, field.TypeString, value)
	}
	if _u.mutation.QuoteMintCleared() {
		_spec.ClearField(paperposition.FieldQuoteMint, field.TypeString)
	}
	if value, ok := _u.mutation.MintAddress(); ok {
		_spec.SetField(paperposition.FieldMintAddress, field.TypeString, value)
	}
	if _u.mutation.MintAddressCleared() {
		_spec.ClearField(paperposition.FieldMintAddress, field.TypeString)
	}
	if value, ok := _u.mutation.EntryPrice(); ok {
		_spec.SetField(paperposition.FieldEntryPrice, field.TypeString, value)
	}
	if _u.mutation.EntryPriceCleared() {
		_spec.ClearField(paperposition.FieldEntryPrice, field.TypeString)
	}
	if value, ok := _u.mutation.EntryInputAmount(); ok {
		_spec.SetField(paperposition.FieldEntryInputAmount, field.TypeString, value)
	}
	if _u.mutation.EntryInputAmountCleared() {
		_spec.ClearField(paperposition.FieldEntryInputAmount, field.TypeString)
	}
	if value, ok := _u.mutation.EntryNetworkFeeMicros(); ok {
		_spec.SetField(paperposition.FieldEntryNetworkFeeMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntryNetworkFeeMicros(); ok {
		_spec.AddField(paperposition.FieldEntryNetworkFeeMicros, field.TypeInt64, value)
	}
	if _u.mutation.EntryNetworkFeeMicrosCleared() {
		_spec.ClearField(paperposition.FieldEntryNetworkFeeMicros, field.TypeInt64)
	}
	if value, ok := _u.mutation.EntryPriorityFeeMicros(); ok {
		_spec.SetField(paperposition.FieldEntryPriorityFeeMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntryPriorityFeeMicros(); ok {
		_spec.AddField(paperposition.FieldEntryPriorityFeeMicros, field.TypeInt64, value)
	}
	if _u.mutation.EntryPriorityFeeMicrosCleared() {
		_spec.ClearField(paperposition.FieldEntryPriorityFeeMicros, field.TypeInt64)
	}
	if value, ok := _u.mutation.TokenQuantity(); ok {
		_spec.SetField(paperposition.FieldTokenQuantity, field.TypeString, value)
	}
	if _u.mutation.TokenQuantityCleared() {
		_spec.ClearField(paperposition.FieldTokenQuantity, field.TypeString)
	}
	if value, ok := _u.mutation.OpenedAt(); ok {
		_spec.SetField(paperposition.FieldOpenedAt, field.TypeTime, value)
	}
	if _u.mutation.OpenedAtCleared() {
		_spec.ClearField(paperposition.FieldOpenedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(paperposition.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(paperposition.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paperposition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CandidateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paperposition.CandidateTable,
			Columns: []string{paperposition.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paperposition.CandidateTable,
			Columns: []string{paperposition.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DecisionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paperposition.DecisionTable,
			Columns: []string{paperposition.DecisionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DecisionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paperposition.DecisionTable,
			Columns: []string{paperposition.DecisionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.MarksTable,
			Columns: []string{paperposition.MarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMarksIDs(); len(nodes) > 0 && !_u.mutation.MarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.MarksTable,
			Columns: []string{paperposition.MarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.MarksTable,
			Columns: []string{paperposition.MarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.EventsTable,
			Columns: []string{paperposition.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.EventsTable,
			Columns: []string{paperposition.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.EventsTable,
			Columns: []string{paperposition.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paperposition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaperPositionUpdateOne is the builder for updating a single PaperPosition entity.
type PaperPositionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaperPositionMutation
}

// SetState sets the "state" field.
func (_u *PaperPositionUpdateOne) SetState(v paperposition.State) *PaperPositionUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableState(v *paperposition.State) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetNotionalMicros sets the "notional_micros" field.
func (_u *PaperPositionUpdateOne) SetNotionalMicros(v int64) *PaperPositionUpdateOne {
	_u.mutation.ResetNotionalMicros()
	_u.mutation.SetNotionalMicros(v)
	return _u
}

// SetNillableNotionalMicros sets the "notional_micros" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableNotionalMicros(v *int64) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetNotionalMicros(*v)
	}
	return _u
}

// AddNotionalMicros adds value to the "notional_micros" field.
func (_u *PaperPositionUpdateOne) AddNotionalMicros(v int64) *PaperPositionUpdateOne {
	_u.mutation.AddNotionalMicros(v)
	return _u
}

// SetStrategyVersion sets the "strategy_version" field.
func (_u *PaperPositionUpdateOne) SetStrategyVersion(v string) *PaperPositionUpdateOne {
	_u.mutation.SetStrategyVersion(v)
	return _u
}

// SetNillableStrategyVersion sets the "strategy_version" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableStrategyVersion(v *string) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetStrategyVersion(*v)
	}
	return _u
}

// SetNoRouteCount sets the "no_route_count" field.
func (_u *PaperPositionUpdateOne) SetNoRouteCount(v int) *PaperPositionUpdateOne {
	_u.mutation.ResetNoRouteCount()
	_u.mutation.SetNoRouteCount(v)
	return _u
}

// SetNillableNoRouteCount sets the "no_route_count" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableNoRouteCount(v *int) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetNoRouteCount(*v)
	}
	return _u
}

// AddNoRouteCount adds value to the "no_route_count" field.
func (_u *PaperPositionUpdateOne) AddNoRouteCount(v int) *PaperPositionUpdateOne {
	_u.mutation.AddNoRouteCount(v)
	return _u
}

// SetQuoteMint sets the "quote_mint" field.
func (_u *PaperPositionUpdateOne) SetQuoteMint(v string) *PaperPositionUpdateOne {
	_u.mutation.SetQuoteMint(v)
	return _u
}

// SetNillableQuoteMint sets the "quote_mint" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableQuoteMint(v *string) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetQuoteMint(*v)
	}
	return _u
}

// ClearQuoteMint clears the value of the "quote_mint" field.
func (_u *PaperPositionUpdateOne) ClearQuoteMint() *PaperPositionUpdateOne {
	_u.mutation.ClearQuoteMint()
	return _u
}

// SetMintAddress sets the "mint_address" field.
func (_u *PaperPositionUpdateOne) SetMintAddress(v string) *PaperPositionUpdateOne {
	_u.mutation.SetMintAddress(v)
	return _u
}

// SetNillableMintAddress sets the "mint_address" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableMintAddress(v *string) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetMintAddress(*v)
	}
	return _u
}

// ClearMintAddress clears the value of the "mint_address" field.
func (_u *PaperPositionUpdateOne) ClearMintAddress() *PaperPositionUpdateOne {
	_u.mutation.ClearMintAddress()
	return _u
}

// SetEntryPrice sets the "entry_price" field.
func (_u *PaperPositionUpdateOne) SetEntryPrice(v string) *PaperPositionUpdateOne {
	_u.mutation.SetEntryPrice(v)
	return _u
}

// SetNillableEntryPrice sets the "entry_price" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableEntryPrice(v *string) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetEntryPrice(*v)
	}
	return _u
}

// ClearEntryPrice clears the value of the "entry_price" field.
func (_u *PaperPositionUpdateOne) ClearEntryPrice() *PaperPositionUpdateOne {
	_u.mutation.ClearEntryPrice()
	return _u
}

// SetEntryInputAmount sets the "entry_input_amount" field.
func (_u *PaperPositionUpdateOne) SetEntryInputAmount(v string) *PaperPositionUpdateOne {
	_u.mutation.SetEntryInputAmount(v)
	return _u
}

// SetNillableEntryInputAmount sets the "entry_input_amount" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableEntryInputAmount(v *string) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetEntryInputAmount(*v)
	}
	return _u
}

// ClearEntryInputAmount clears the value of the "entry_input_amount" field.
func (_u *PaperPositionUpdateOne) ClearEntryInputAmount() *PaperPositionUpdateOne {
	_u.mutation.ClearEntryInputAmount()
	return _u
}

// SetEntryNetworkFeeMicros sets the "entry_network_fee_micros" field.
func (_u *PaperPositionUpdateOne) SetEntryNetworkFeeMicros(v int64) *PaperPositionUpdateOne {
	_u.mutation.ResetEntryNetworkFeeMicros()
	_u.mutation.SetEntryNetworkFeeMicros(v)
	return _u
}

// SetNillableEntryNetworkFeeMicros sets the "entry_network_fee_micros" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableEntryNetworkFeeMicros(v *int64) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetEntryNetworkFeeMicros(*v)
	}
	return _u
}

// AddEntryNetworkFeeMicros adds value to the "entry_network_fee_micros" field.
func (_u *PaperPositionUpdateOne) AddEntryNetworkFeeMicros(v int64) *PaperPositionUpdateOne {
	_u.mutation.AddEntryNetworkFeeMicros(v)
	return _u
}

// ClearEntryNetworkFeeMicros clears the value of the "entry_network_fee_micros" field.
func (_u *PaperPositionUpdateOne) ClearEntryNetworkFeeMicros() *PaperPositionUpdateOne {
	_u.mutation.ClearEntryNetworkFeeMicros()
	return _u
}

// SetEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field.
func (_u *PaperPositionUpdateOne) SetEntryPriorityFeeMicros(v int64) *PaperPositionUpdateOne {
	_u.mutation.ResetEntryPriorityFeeMicros()
	_u.mutation.SetEntryPriorityFeeMicros(v)
	return _u
}

// SetNillableEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableEntryPriorityFeeMicros(v *int64) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetEntryPriorityFeeMicros(*v)
	}
	return _u
}

// AddEntryPriorityFeeMicros adds value to the "entry_priority_fee_micros" field.
func (_u *PaperPositionUpdateOne) AddEntryPriorityFeeMicros(v int64) *PaperPositionUpdateOne {
	_u.mutation.AddEntryPriorityFeeMicros(v)
	return _u
}

// ClearEntryPriorityFeeMicros clears the value of the "entry_priority_fee_micros" field.
func (_u *PaperPositionUpdateOne) ClearEntryPriorityFeeMicros() *PaperPositionUpdateOne {
	_u.mutation.ClearEntryPriorityFeeMicros()
	return _u
}

// SetTokenQuantity sets the "token_quantity" field.
func (_u *PaperPositionUpdateOne) SetTokenQuantity(v string) *PaperPositionUpdateOne {
	_u.mutation.SetTokenQuantity(v)
	return _u
}

// SetNillableTokenQuantity sets the "token_quantity" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableTokenQuantity(v *string) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetTokenQuantity(*v)
	}
	return _u
}

// ClearTokenQuantity clears the value of the "token_quantity" field.
func (_u *PaperPositionUpdateOne) ClearTokenQuantity() *PaperPositionUpdateOne {
	_u.mutation.ClearTokenQuantity()
	return _u
}

// SetOpenedAt sets the "opened_at" field.
func (_u *PaperPositionUpdateOne) SetOpenedAt(v time.Time) *PaperPositionUpdateOne {
	_u.mutation.SetOpenedAt(v)
	return _u
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableOpenedAt(v *time.Time) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetOpenedAt(*v)
	}
	return _u
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (_u *PaperPositionUpdateOne) ClearOpenedAt() *PaperPositionUpdateOne {
	_u.mutation.ClearOpenedAt()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *PaperPositionUpdateOne) SetClosedAt(v time.Time) *PaperPositionUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *PaperPositionUpdateOne) SetNillableClosedAt(v *time.Time) *PaperPositionUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *PaperPositionUpdateOne) ClearClosedAt() *PaperPositionUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaperPositionUpdateOne) SetUpdatedAt(v time.Time) *PaperPositionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_u *PaperPositionUpdateOne) SetCandidateID(id int) *PaperPositionUpdateOne {
	_u.mutation.SetCandidateID(id)
	return _u
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_u *PaperPositionUpdateOne) SetCandidate(v *Candidate) *PaperPositionUpdateOne {
	return _u.SetCandidateID(v.ID)
}

// SetDecisionID sets the "decision" edge to the TradeDecision entity by ID.
func (_u *PaperPositionUpdateOne) SetDecisionID(id int) *PaperPositionUpdateOne {
	_u.mutation.SetDecisionID(id)
	return _u
}

// SetDecision sets the "decision" edge to the TradeDecision entity.
func (_u *PaperPositionUpdateOne) SetDecision(v *TradeDecision) *PaperPositionUpdateOne {
	return _u.SetDecisionID(v.ID)
}

// AddMarkIDs adds the "marks" edge to the PositionMark entity by IDs.
func (_u *PaperPositionUpdateOne) AddMarkIDs(ids ...int) *PaperPositionUpdateOne {
	_u.mutation.AddMarkIDs(ids...)
	return _u
}

// AddMarks adds the "marks" edges to the PositionMark entity.
func (_u *PaperPositionUpdateOne) AddMarks(v ...*PositionMark) *PaperPositionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMarkIDs(ids...)
}

// AddEventIDs adds the "events" edge to the PositionEvent entity by IDs.
func (_u *PaperPositionUpdateOne) AddEventIDs(ids ...int) *PaperPositionUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the PositionEvent entity.
func (_u *PaperPositionUpdateOne) AddEvents(v ...*PositionEvent) *PaperPositionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the PaperPositionMutation object of the builder.
func (_u *PaperPositionUpdateOne) Mutation() *PaperPositionMutation {
	return _u.mutation
}

// ClearCandidate clears the "candidate" edge to the Candidate entity.
func (_u *PaperPositionUpdateOne) ClearCandidate() *PaperPositionUpdateOne {
	_u.mutation.ClearCandidate()
	return _u
}

// ClearDecision clears the "decision" edge to the TradeDecision entity.
func (_u *PaperPositionUpdateOne) ClearDecision() *PaperPositionUpdateOne {
	_u.mutation.ClearDecision()
	return _u
}

// ClearMarks clears all "marks" edges to the PositionMark entity.
func (_u *PaperPositionUpdateOne) ClearMarks() *PaperPositionUpdateOne {
	_u.mutation.ClearMarks()
	return _u
}

// RemoveMarkIDs removes the "marks" edge to PositionMark entities by IDs.
func (_u *PaperPositionUpdateOne) RemoveMarkIDs(ids ...int) *PaperPositionUpdateOne {
	_u.mutation.RemoveMarkIDs(ids...)
	return _u
}

// RemoveMarks removes "marks" edges to PositionMark entities.
func (_u *PaperPositionUpdateOne) RemoveMarks(v ...*PositionMark) *PaperPositionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMarkIDs(ids...)
}

// ClearEvents clears all "events" edges to the PositionEvent entity.
func (_u *PaperPositionUpdateOne) ClearEvents() *PaperPositionUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to PositionEvent entities by IDs.
func (_u *PaperPositionUpdateOne) RemoveEventIDs(ids ...int) *PaperPositionUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to PositionEvent entities.
func (_u *PaperPositionUpdateOne) RemoveEvents(v ...*PositionEvent) *PaperPositionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the PaperPositionUpdate builder.
func (_u *PaperPositionUpdateOne) Where(ps ...predicate.PaperPosition) *PaperPositionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaperPositionUpdateOne) Select(field string, fields ...string) *PaperPositionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaperPosition entity.
func (_u *PaperPositionUpdateOne) Save(ctx context.Context) (*PaperPosition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaperPositionUpdateOne) SaveX(ctx context.Context) *PaperPosition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaperPositionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaperPositionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaperPositionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paperposition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaperPositionUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := paperposition.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NotionalMicros(); ok {
		if err := paperposition.NotionalMicrosValidator(v); err != nil {
			return &ValidationError{Name: "notional_micros", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.notional_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyVersion(); ok {
		if err := paperposition.StrategyVersionValidator(v); err != nil {
			return &ValidationError{Name: "strategy_version", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.strategy_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NoRouteCount(); ok {
		if err := paperposition.NoRouteCountValidator(v); err != nil {
			return &ValidationError{Name: "no_route_count", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.no_route_count": %w`, err)}
		}
	}
	if _u.mutation.CandidateCleared() && len(_u.mutation.CandidateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaperPosition.candidate"`)
	}
	if _u.mutation.DecisionCleared() && len(_u.mutation.DecisionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaperPosition.decision"`)
	}
	return nil
}

func (_u *PaperPositionUpdateOne) sqlSave(ctx context.Context) (_node *PaperPosition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paperposition.Table, paperposition.Columns, sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaperPosition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paperposition.FieldID)
		for _, f := range fields {
			if !paperposition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paperposition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(paperposition.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NotionalMicros(); ok {
		_spec.SetField(paperposition.FieldNotionalMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNotionalMicros(); ok {
		_spec.AddField(paperposition.FieldNotionalMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StrategyVersion(); ok {
		_spec.SetField(paperposition.FieldStrategyVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.NoRouteCount(); ok {
		_spec.SetField(paperposition.FieldNoRouteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNoRouteCount(); ok {
		_spec.AddField(paperposition.FieldNoRouteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuoteMint(); ok {
		_spec.SetField(paperposition.FieldQuoteMint, field.TypeString, value)
	}
	if _u.mutation.QuoteMintCleared() {
		_spec.ClearField(paperposition.FieldQuoteMint, field.TypeString)
	}
	if value, ok := _u.mutation.MintAddress(); ok {
		_spec.SetField(paperposition.FieldMintAddress, field.TypeString, value)
	}
	if _u.mutation.MintAddressCleared() {
		_spec.ClearField(paperposition.FieldMintAddress, field.TypeString)
	}
	if value, ok := _u.mutation.EntryPrice(); ok {
		_spec.SetField(paperposition.FieldEntryPrice, field.TypeString, value)
	}
	if _u.mutation.EntryPriceCleared() {
		_spec.ClearField(paperposition.FieldEntryPrice, field.TypeString)
	}
	if value, ok := _u.mutation.EntryInputAmount(); ok {
		_spec.SetField(paperposition.FieldEntryInputAmount, field.TypeString, value)
	}
	if _u.mutation.EntryInputAmountCleared() {
		_spec.ClearField(paperposition.FieldEntryInputAmount, field.TypeString)
	}
	if value, ok := _u.mutation.EntryNetworkFeeMicros(); ok {
		_spec.SetField(paperposition.FieldEntryNetworkFeeMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntryNetworkFeeMicros(); ok {
		_spec.AddField(paperposition.FieldEntryNetworkFeeMicros, field.TypeInt64, value)
	}
	if _u.mutation.EntryNetworkFeeMicrosCleared() {
		_spec.ClearField(paperposition.FieldEntryNetworkFeeMicros, field.TypeInt64)
	}
	if value, ok := _u.mutation.EntryPriorityFeeMicros(); ok {
		_spec.SetField(paperposition.FieldEntryPriorityFeeMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntryPriorityFeeMicros(); ok {
		_spec.AddField(paperposition.FieldEntryPriorityFeeMicros, field.TypeInt64, value)
	}
	if _u.mutation.EntryPriorityFeeMicrosCleared() {
		_spec.ClearField(paperposition.FieldEntryPriorityFeeMicros, field.TypeInt64)
	}
	if value, ok := _u.mutation.TokenQuantity(); ok {
		_spec.SetField(paperposition.FieldTokenQuantity, field.TypeString, value)
	}
	if _u.mutation.TokenQuantityCleared() {
		_spec.ClearField(paperposition.FieldTokenQuantity, field.TypeString)
	}
	if value, ok := _u.mutation.OpenedAt(); ok {
		_spec.SetField(paperposition.FieldOpenedAt, field.TypeTime, value)
	}
	if _u.mutation.OpenedAtCleared() {
		_spec.ClearField(paperposition.FieldOpenedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(paperposition.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(paperposition.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paperposition.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CandidateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paperposition.CandidateTable,
			Columns: []string{paperposition.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paperposition.CandidateTable,
			Columns: []string{paperposition.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DecisionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paperposition.DecisionTable,
			Columns: []string{paperposition.DecisionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DecisionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paperposition.DecisionTable,
			Columns: []string{paperposition.DecisionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.MarksTable,
			Columns: []string{paperposition.MarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMarksIDs(); len(nodes) > 0 && !_u.mutation.MarksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.MarksTable,
			Columns: []string{paperposition.MarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.MarksTable,
			Columns: []string{paperposition.MarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.EventsTable,
			Columns: []string{paperposition.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.EventsTable,
			Columns: []string{paperposition.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.EventsTable,
			Columns: []string{paperposition.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaperPosition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paperposition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
