// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/positionevent"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/positionmark"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/tradedecision"
)

// PaperPositionCreate is the builder for creating a PaperPosition entity.
type PaperPositionCreate struct {
	config
	mutation *PaperPositionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetState sets the "state" field.
func (_c *PaperPositionCreate) SetState(v paperposition.State) *PaperPositionCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNotionalMicros sets the "notional_micros" field.
func (_c *PaperPositionCreate) SetNotionalMicros(v int64) *PaperPositionCreate {
	_c.mutation.SetNotionalMicros(v)
	return _c
}

// SetStrategyVersion sets the "strategy_version" field.
func (_c *PaperPositionCreate) SetStrategyVersion(v string) *PaperPositionCreate {
	_c.mutation.SetStrategyVersion(v)
	return _c
}

// SetNillableStrategyVersion sets the "strategy_version" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableStrategyVersion(v *string) *PaperPositionCreate {
	if v != nil {
		_c.SetStrategyVersion(*v)
	}
	return _c
}

// SetNoRouteCount sets the "no_route_count" field.
func (_c *PaperPositionCreate) SetNoRouteCount(v int) *PaperPositionCreate {
	_c.mutation.SetNoRouteCount(v)
	return _c
}

// SetNillableNoRouteCount sets the "no_route_count" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableNoRouteCount(v *int) *PaperPositionCreate {
	if v != nil {
		_c.SetNoRouteCount(*v)
	}
	return _c
}

// SetQuoteMint sets the "quote_mint" field.
func (_c *PaperPositionCreate) SetQuoteMint(v string) *PaperPositionCreate {
	_c.mutation.SetQuoteMint(v)
	return _c
}

// SetNillableQuoteMint sets the "quote_mint" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableQuoteMint(v *string) *PaperPositionCreate {
	if v != nil {
		_c.SetQuoteMint(*v)
	}
	return _c
}

// SetMintAddress sets the "mint_address" field.
func (_c *PaperPositionCreate) SetMintAddress(v string) *PaperPositionCreate {
	_c.mutation.SetMintAddress(v)
	return _c
}

// SetNillableMintAddress sets the "mint_address" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableMintAddress(v *string) *PaperPositionCreate {
	if v != nil {
		_c.SetMintAddress(*v)
	}
	return _c
}

// SetEntryPrice sets the "entry_price" field.
func (_c *PaperPositionCreate) SetEntryPrice(v string) *PaperPositionCreate {
	_c.mutation.SetEntryPrice(v)
	return _c
}

// SetNillableEntryPrice sets the "entry_price" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableEntryPrice(v *string) *PaperPositionCreate {
	if v != nil {
		_c.SetEntryPrice(*v)
	}
	return _c
}

// SetEntryInputAmount sets the "entry_input_amount" field.
func (_c *PaperPositionCreate) SetEntryInputAmount(v string) *PaperPositionCreate {
	_c.mutation.SetEntryInputAmount(v)
	return _c
}

// SetNillableEntryInputAmount sets the "entry_input_amount" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableEntryInputAmount(v *string) *PaperPositionCreate {
	if v != nil {
		_c.SetEntryInputAmount(*v)
	}
	return _c
}

// SetEntryNetworkFeeMicros sets the "entry_network_fee_micros" field.
func (_c *PaperPositionCreate) SetEntryNetworkFeeMicros(v int64) *PaperPositionCreate {
	_c.mutation.SetEntryNetworkFeeMicros(v)
	return _c
}

// SetNillableEntryNetworkFeeMicros sets the "entry_network_fee_micros" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableEntryNetworkFeeMicros(v *int64) *PaperPositionCreate {
	if v != nil {
		_c.SetEntryNetworkFeeMicros(*v)
	}
	return _c
}

// SetEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field.
func (_c *PaperPositionCreate) SetEntryPriorityFeeMicros(v int64) *PaperPositionCreate {
	_c.mutation.SetEntryPriorityFeeMicros(v)
	return _c
}

// SetNillableEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableEntryPriorityFeeMicros(v *int64) *PaperPositionCreate {
	if v != nil {
		_c.SetEntryPriorityFeeMicros(*v)
	}
	return _c
}

// SetTokenQuantity sets the "token_quantity" field.
func (_c *PaperPositionCreate) SetTokenQuantity(v string) *PaperPositionCreate {
	_c.mutation.SetTokenQuantity(v)
	return _c
}

// SetNillableTokenQuantity sets the "token_quantity" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableTokenQuantity(v *string) *PaperPositionCreate {
	if v != nil {
		_c.SetTokenQuantity(*v)
	}
	return _c
}

// SetOpenedAt sets the "opened_at" field.
func (_c *PaperPositionCreate) SetOpenedAt(v time.Time) *PaperPositionCreate {
	_c.mutation.SetOpenedAt(v)
	return _c
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableOpenedAt(v *time.Time) *PaperPositionCreate {
	if v != nil {
		_c.SetOpenedAt(*v)
	}
	return _c
}

// SetClosedAt sets the "closed_at" field.
func (_c *PaperPositionCreate) SetClosedAt(v time.Time) *PaperPositionCreate {
	_c.mutation.SetClosedAt(v)
	return _c
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableClosedAt(v *time.Time) *PaperPositionCreate {
	if v != nil {
		_c.SetClosedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaperPositionCreate) SetCreatedAt(v time.Time) *PaperPositionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableCreatedAt(v *time.Time) *PaperPositionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaperPositionCreate) SetUpdatedAt(v time.Time) *PaperPositionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableUpdatedAt(v *time.Time) *PaperPositionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_c *PaperPositionCreate) SetCandidateID(id int) *PaperPositionCreate {
	_c.mutation.SetCandidateID(id)
	return _c
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_c *PaperPositionCreate) SetCandidate(v *Candidate) *PaperPositionCreate {
	return _c.SetCandidateID(v.ID)
}

// SetDecisionID sets the "decision" edge to the TradeDecision entity by ID.
func (_c *PaperPositionCreate) SetDecisionID(id int) *PaperPositionCreate {
	_c.mutation.SetDecisionID(id)
	return _c
}

// SetDecision sets the "decision" edge to the TradeDecision entity.
func (_c *PaperPositionCreate) SetDecision(v *TradeDecision) *PaperPositionCreate {
	return _c.SetDecisionID(v.ID)
}

// AddMarkIDs adds the "marks" edge to the PositionMark entity by IDs.
func (_c *PaperPositionCreate) AddMarkIDs(ids ...int) *PaperPositionCreate {
	_c.mutation.AddMarkIDs(ids...)
	return _c
}

// AddMarks adds the "marks" edges to the PositionMark entity.
func (_c *PaperPositionCreate) AddMarks(v ...*PositionMark) *PaperPositionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMarkIDs(ids...)
}

// AddEventIDs adds the "events" edge to the PositionEvent entity by IDs.
func (_c *PaperPositionCreate) AddEventIDs(ids ...int) *PaperPositionCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the PositionEvent entity.
func (_c *PaperPositionCreate) AddEvents(v ...*PositionEvent) *PaperPositionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the PaperPositionMutation object of the builder.
func (_c *PaperPositionCreate) Mutation() *PaperPositionMutation {
	return _c.mutation
}

// Save creates the PaperPosition in the database.
func (_c *PaperPositionCreate) Save(ctx context.Context) (*PaperPosition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaperPositionCreate) SaveX(ctx context.Context) *PaperPosition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaperPositionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaperPositionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaperPositionCreate) defaults() {
	if _, ok := _c.mutation.StrategyVersion(); !ok {
		v := paperposition.DefaultStrategyVersion
		_c.mutation.SetStrategyVersion(v)
	}
	if _, ok := _c.mutation.NoRouteCount(); !ok {
		v := paperposition.DefaultNoRouteCount
		_c.mutation.SetNoRouteCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paperposition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paperposition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaperPositionCreate) check() error {
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "PaperPosition.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := paperposition.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotionalMicros(); !ok {
		return &ValidationError{Name: "notional_micros", err: errors.New(`ent: missing required field "PaperPosition.notional_micros"`)}
	}
	if v, ok := _c.mutation.NotionalMicros(); ok {
		if err := paperposition.NotionalMicrosValidator(v); err != nil {
			return &ValidationError{Name: "notional_micros", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.notional_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StrategyVersion(); !ok {
		return &ValidationError{Name: "strategy_version", err: errors.New(`ent: missing required field "PaperPosition.strategy_version"`)}
	}
	if v, ok := _c.mutation.StrategyVersion(); ok {
		if err := paperposition.StrategyVersionValidator(v); err != nil {
			return &ValidationError{Name: "strategy_version", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.strategy_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NoRouteCount(); !ok {
		return &ValidationError{Name: "no_route_count", err: errors.New(`ent: missing required field "PaperPosition.no_route_count"`)}
	}
	if v, ok := _c.mutation.NoRouteCount(); ok {
		if err := paperposition.NoRouteCountValidator(v); err != nil {
			return &ValidationError{Name: "no_route_count", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.no_route_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaperPosition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaperPosition.updated_at"`)}
	}
	if len(_c.mutation.CandidateIDs()) == 0 {
		return &ValidationError{Name: "candidate", err: errors.New(`ent: missing required edge "PaperPosition.candidate"`)}
	}
	if len(_c.mutation.DecisionIDs()) == 0 {
		return &ValidationError{Name: "decision", err: errors.New(`ent: missing required edge "PaperPosition.decision"`)}
	}
	return nil
}

func (_c *PaperPositionCreate) sqlSave(ctx context.Context) (*PaperPosition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaperPositionCreate) createSpec() (*PaperPosition, *sqlgraph.CreateSpec) {
	var (
		_node = &PaperPosition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paperposition.Table, sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(paperposition.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.NotionalMicros(); ok {
		_spec.SetField(paperposition.FieldNotionalMicros, field.TypeInt64, value)
		_node.NotionalMicros = value
	}
	if value, ok := _c.mutation.StrategyVersion(); ok {
		_spec.SetField(paperposition.FieldStrategyVersion, field.TypeString, value)
		_node.StrategyVersion = value
	}
	if value, ok := _c.mutation.NoRouteCount(); ok {
		_spec.SetField(paperposition.FieldNoRouteCount, field.TypeInt, value)
		_node.NoRouteCount = value
	}
	if value, ok := _c.mutation.QuoteMint(); ok {
		_spec.SetField(paperposition.FieldQuoteMint, field.TypeString, value)
		_node.QuoteMint = &value
	}
	if value, ok := _c.mutation.MintAddress(); ok {
		_spec.SetField(paperposition.FieldMintAddress, field.TypeString, value)
		_node.MintAddress = &value
	}
	if value, ok := _c.mutation.EntryPrice(); ok {
		_spec.SetField(paperposition.FieldEntryPrice, field.TypeString, value)
		_node.EntryPrice = &value
	}
	if value, ok := _c.mutation.EntryInputAmount(); ok {
		_spec.SetField(paperposition.FieldEntryInputAmount, field.TypeString, value)
		_node.EntryInputAmount = &value
	}
	if value, ok := _c.mutation.EntryNetworkFeeMicros(); ok {
		_spec.SetField(paperposition.FieldEntryNetworkFeeMicros, field.TypeInt64, value)
		_node.EntryNetworkFeeMicros = &value
	}
	if value, ok := _c.mutation.EntryPriorityFeeMicros(); ok {
		_spec.SetField(paperposition.FieldEntryPriorityFeeMicros, field.TypeInt64, value)
		_node.EntryPriorityFeeMicros = &value
	}
	if value, ok := _c.mutation.TokenQuantity(); ok {
		_spec.SetField(paperposition.FieldTokenQuantity, field.TypeString, value)
		_node.TokenQuantity = &value
	}
	if value, ok := _c.mutation.OpenedAt(); ok {
		_spec.SetField(paperposition.FieldOpenedAt, field.TypeTime, value)
		_node.OpenedAt = &value
	}
	if value, ok := _c.mutation.ClosedAt(); ok {
		_spec.SetField(paperposition.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paperposition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paperposition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paperposition.CandidateTable,
			Columns: []string{paperposition.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.candidate_positions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DecisionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paperposition.DecisionTable,
			Columns: []string{paperposition.DecisionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.trade_decision_position = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.MarksTable,
			Columns: []string{paperposition.MarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.EventsTable,
			Columns: []string{paperposition.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaperPosition.Create().
//		SetState(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaperPositionUpsert) {
//			SetState(v+v).
//		}).
//		Exec(ctx)
func (_c *PaperPositionCreate) OnConflict(opts ...sql.ConflictOption) *PaperPositionUpsertOne {
	_c.conflict = opts
	return &PaperPositionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaperPosition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaperPositionCreate) OnConflictColumns(columns ...string) *PaperPositionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaperPositionUpsertOne{
		create: _c,
	}
}

type (
	// PaperPositionUpsertOne is the builder for "upsert"-ing
	//  one PaperPosition node.
	PaperPositionUpsertOne struct {
		create *PaperPositionCreate
	}

	// PaperPositionUpsert is the "OnConflict" setter.
	PaperPositionUpsert struct {
		*sql.UpdateSet
	}
)

// SetState sets the "state" field.
func (u *PaperPositionUpsert) SetState(v paperposition.State) *PaperPositionUpsert {
	u.Set(paperposition.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateState() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldState)
	return u
}

// SetNotionalMicros sets the "notional_micros" field.
func (u *PaperPositionUpsert) SetNotionalMicros(v int64) *PaperPositionUpsert {
	u.Set(paperposition.FieldNotionalMicros, v)
	return u
}

// UpdateNotionalMicros sets the "notional_micros" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateNotionalMicros() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldNotionalMicros)
	return u
}

// AddNotionalMicros adds v to the "notional_micros" field.
func (u *PaperPositionUpsert) AddNotionalMicros(v int64) *PaperPositionUpsert {
	u.Add(paperposition.FieldNotionalMicros, v)
	return u
}

// SetStrategyVersion sets the "strategy_version" field.
func (u *PaperPositionUpsert) SetStrategyVersion(v string) *PaperPositionUpsert {
	u.Set(paperposition.FieldStrategyVersion, v)
	return u
}

// UpdateStrategyVersion sets the "strategy_version" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateStrategyVersion() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldStrategyVersion)
	return u
}

// SetNoRouteCount sets the "no_route_count" field.
func (u *PaperPositionUpsert) SetNoRouteCount(v int) *PaperPositionUpsert {
	u.Set(paperposition.FieldNoRouteCount, v)
	return u
}

// UpdateNoRouteCount sets the "no_route_count" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateNoRouteCount() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldNoRouteCount)
	return u
}

// AddNoRouteCount adds v to the "no_route_count" field.
func (u *PaperPositionUpsert) AddNoRouteCount(v int) *PaperPositionUpsert {
	u.Add(paperposition.FieldNoRouteCount, v)
	return u
}

// SetQuoteMint sets the "quote_mint" field.
func (u *PaperPositionUpsert) SetQuoteMint(v string) *PaperPositionUpsert {
	u.Set(paperposition.FieldQuoteMint, v)
	return u
}

// UpdateQuoteMint sets the "quote_mint" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateQuoteMint() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldQuoteMint)
	return u
}

// ClearQuoteMint clears the value of the "quote_mint" field.
func (u *PaperPositionUpsert) ClearQuoteMint() *PaperPositionUpsert {
	u.SetNull(paperposition.FieldQuoteMint)
	return u
}

// SetMintAddress sets the "mint_address" field.
func (u *PaperPositionUpsert) SetMintAddress(v string) *PaperPositionUpsert {
	u.Set(paperposition.FieldMintAddress, v)
	return u
}

// UpdateMintAddress sets the "mint_address" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateMintAddress() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldMintAddress)
	return u
}

// ClearMintAddress clears the value of the "mint_address" field.
func (u *PaperPositionUpsert) ClearMintAddress() *PaperPositionUpsert {
	u.SetNull(paperposition.FieldMintAddress)
	return u
}

// SetEntryPrice sets the "entry_price" field.
func (u *PaperPositionUpsert) SetEntryPrice(v string) *PaperPositionUpsert {
	u.Set(paperposition.FieldEntryPrice, v)
	return u
}

// UpdateEntryPrice sets the "entry_price" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateEntryPrice() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldEntryPrice)
	return u
}

// ClearEntryPrice clears the value of the "entry_price" field.
func (u *PaperPositionUpsert) ClearEntryPrice() *PaperPositionUpsert {
	u.SetNull(paperposition.FieldEntryPrice)
	return u
}

// SetEntryInputAmount sets the "entry_input_amount" field.
func (u *PaperPositionUpsert) SetEntryInputAmount(v string) *PaperPositionUpsert {
	u.Set(paperposition.FieldEntryInputAmount, v)
	return u
}

// UpdateEntryInputAmount sets the "entry_input_amount" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateEntryInputAmount() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldEntryInputAmount)
	return u
}

// ClearEntryInputAmount clears the value of the "entry_input_amount" field.
func (u *PaperPositionUpsert) ClearEntryInputAmount() *PaperPositionUpsert {
	u.SetNull(paperposition.FieldEntryInputAmount)
	return u
}

// SetEntryNetworkFeeMicros sets the "entry_network_fee_micros" field.
func (u *PaperPositionUpsert) SetEntryNetworkFeeMicros(v int64) *PaperPositionUpsert {
	u.Set(paperposition.FieldEntryNetworkFeeMicros, v)
	return u
}

// UpdateEntryNetworkFeeMicros sets the "entry_network_fee_micros" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateEntryNetworkFeeMicros() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldEntryNetworkFeeMicros)
	return u
}

// AddEntryNetworkFeeMicros adds v to the "entry_network_fee_micros" field.
func (u *PaperPositionUpsert) AddEntryNetworkFeeMicros(v int64) *PaperPositionUpsert {
	u.Add(paperposition.FieldEntryNetworkFeeMicros, v)
	return u
}

// ClearEntryNetworkFeeMicros clears the value of the "entry_network_fee_micros" field.
func (u *PaperPositionUpsert) ClearEntryNetworkFeeMicros() *PaperPositionUpsert {
	u.SetNull(paperposition.FieldEntryNetworkFeeMicros)
	return u
}

// SetEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field.
func (u *PaperPositionUpsert) SetEntryPriorityFeeMicros(v int64) *PaperPositionUpsert {
	u.Set(paperposition.FieldEntryPriorityFeeMicros, v)
	return u
}

// UpdateEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateEntryPriorityFeeMicros() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldEntryPriorityFeeMicros)
	return u
}

// AddEntryPriorityFeeMicros adds v to the "entry_priority_fee_micros" field.
func (u *PaperPositionUpsert) AddEntryPriorityFeeMicros(v int64) *PaperPositionUpsert {
	u.Add(paperposition.FieldEntryPriorityFeeMicros, v)
	return u
}

// ClearEntryPriorityFeeMicros clears the value of the "entry_priority_fee_micros" field.
func (u *PaperPositionUpsert) ClearEntryPriorityFeeMicros() *PaperPositionUpsert {
	u.SetNull(paperposition.FieldEntryPriorityFeeMicros)
	return u
}

// SetTokenQuantity sets the "token_quantity" field.
func (u *PaperPositionUpsert) SetTokenQuantity(v string) *PaperPositionUpsert {
	u.Set(paperposition.FieldTokenQuantity, v)
	return u
}

// UpdateTokenQuantity sets the "token_quantity" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateTokenQuantity() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldTokenQuantity)
	return u
}

// ClearTokenQuantity clears the value of the "token_quantity" field.
func (u *PaperPositionUpsert) ClearTokenQuantity() *PaperPositionUpsert {
	u.SetNull(paperposition.FieldTokenQuantity)
	return u
}

// SetOpenedAt sets the "opened_at" field.
func (u *PaperPositionUpsert) SetOpenedAt(v time.Time) *PaperPositionUpsert {
	u.Set(paperposition.FieldOpenedAt, v)
	return u
}

// UpdateOpenedAt sets the "opened_at" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateOpenedAt() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldOpenedAt)
	return u
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (u *PaperPositionUpsert) ClearOpenedAt() *PaperPositionUpsert {
	u.SetNull(paperposition.FieldOpenedAt)
	return u
}

// SetClosedAt sets the "closed_at" field.
func (u *PaperPositionUpsert) SetClosedAt(v time.Time) *PaperPositionUpsert {
	u.Set(paperposition.FieldClosedAt, v)
	return u
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateClosedAt() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldClosedAt)
	return u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *PaperPositionUpsert) ClearClosedAt() *PaperPositionUpsert {
	u.SetNull(paperposition.FieldClosedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaperPositionUpsert) SetUpdatedAt(v time.Time) *PaperPositionUpsert {
	u.Set(paperposition.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaperPositionUpsert) UpdateUpdatedAt() *PaperPositionUpsert {
	u.SetExcluded(paperposition.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaperPosition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaperPositionUpsertOne) UpdateNewValues() *PaperPositionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paperposition.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaperPosition.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaperPositionUpsertOne) Ignore() *PaperPositionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaperPositionUpsertOne) DoNothing() *PaperPositionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaperPositionCreate.OnConflict
// documentation for more info.
func (u *PaperPositionUpsertOne) Update(set func(*PaperPositionUpsert)) *PaperPositionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaperPositionUpsert{UpdateSet: update})
	}))
	return u
}

// SetState sets the "state" field.
func (u *PaperPositionUpsertOne) SetState(v paperposition.State) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateState() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateState()
	})
}

// SetNotionalMicros sets the "notional_micros" field.
func (u *PaperPositionUpsertOne) SetNotionalMicros(v int64) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetNotionalMicros(v)
	})
}

// AddNotionalMicros adds v to the "notional_micros" field.
func (u *PaperPositionUpsertOne) AddNotionalMicros(v int64) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.AddNotionalMicros(v)
	})
}

// UpdateNotionalMicros sets the "notional_micros" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateNotionalMicros() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateNotionalMicros()
	})
}

// SetStrategyVersion sets the "strategy_version" field.
func (u *PaperPositionUpsertOne) SetStrategyVersion(v string) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetStrategyVersion(v)
	})
}

// UpdateStrategyVersion sets the "strategy_version" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateStrategyVersion() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateStrategyVersion()
	})
}

// SetNoRouteCount sets the "no_route_count" field.
func (u *PaperPositionUpsertOne) SetNoRouteCount(v int) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetNoRouteCount(v)
	})
}

// AddNoRouteCount adds v to the "no_route_count" field.
func (u *PaperPositionUpsertOne) AddNoRouteCount(v int) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.AddNoRouteCount(v)
	})
}

// UpdateNoRouteCount sets the "no_route_count" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateNoRouteCount() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateNoRouteCount()
	})
}

// SetQuoteMint sets the "quote_mint" field.
func (u *PaperPositionUpsertOne) SetQuoteMint(v string) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetQuoteMint(v)
	})
}

// UpdateQuoteMint sets the "quote_mint" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateQuoteMint() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateQuoteMint()
	})
}

// ClearQuoteMint clears the value of the "quote_mint" field.
func (u *PaperPositionUpsertOne) ClearQuoteMint() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearQuoteMint()
	})
}

// SetMintAddress sets the "mint_address" field.
func (u *PaperPositionUpsertOne) SetMintAddress(v string) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetMintAddress(v)
	})
}

// UpdateMintAddress sets the "mint_address" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateMintAddress() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateMintAddress()
	})
}

// ClearMintAddress clears the value of the "mint_address" field.
func (u *PaperPositionUpsertOne) ClearMintAddress() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearMintAddress()
	})
}

// SetEntryPrice sets the "entry_price" field.
func (u *PaperPositionUpsertOne) SetEntryPrice(v string) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetEntryPrice(v)
	})
}

// UpdateEntryPrice sets the "entry_price" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateEntryPrice() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateEntryPrice()
	})
}

// ClearEntryPrice clears the value of the "entry_price" field.
func (u *PaperPositionUpsertOne) ClearEntryPrice() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearEntryPrice()
	})
}

// SetEntryInputAmount sets the "entry_input_amount" field.
func (u *PaperPositionUpsertOne) SetEntryInputAmount(v string) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetEntryInputAmount(v)
	})
}

// UpdateEntryInputAmount sets the "entry_input_amount" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateEntryInputAmount() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateEntryInputAmount()
	})
}

// ClearEntryInputAmount clears the value of the "entry_input_amount" field.
func (u *PaperPositionUpsertOne) ClearEntryInputAmount() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearEntryInputAmount()
	})
}

// SetEntryNetworkFeeMicros sets the "entry_network_fee_micros" field.
func (u *PaperPositionUpsertOne) SetEntryNetworkFeeMicros(v int64) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetEntryNetworkFeeMicros(v)
	})
}

// AddEntryNetworkFeeMicros adds v to the "entry_network_fee_micros" field.
func (u *PaperPositionUpsertOne) AddEntryNetworkFeeMicros(v int64) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.AddEntryNetworkFeeMicros(v)
	})
}

// UpdateEntryNetworkFeeMicros sets the "entry_network_fee_micros" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateEntryNetworkFeeMicros() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateEntryNetworkFeeMicros()
	})
}

// ClearEntryNetworkFeeMicros clears the value of the "entry_network_fee_micros" field.
func (u *PaperPositionUpsertOne) ClearEntryNetworkFeeMicros() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearEntryNetworkFeeMicros()
	})
}

// SetEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field.
func (u *PaperPositionUpsertOne) SetEntryPriorityFeeMicros(v int64) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetEntryPriorityFeeMicros(v)
	})
}

// AddEntryPriorityFeeMicros adds v to the "entry_priority_fee_micros" field.
func (u *PaperPositionUpsertOne) AddEntryPriorityFeeMicros(v int64) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.AddEntryPriorityFeeMicros(v)
	})
}

// UpdateEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateEntryPriorityFeeMicros() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateEntryPriorityFeeMicros()
	})
}

// ClearEntryPriorityFeeMicros clears the value of the "entry_priority_fee_micros" field.
func (u *PaperPositionUpsertOne) ClearEntryPriorityFeeMicros() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearEntryPriorityFeeMicros()
	})
}

// SetTokenQuantity sets the "token_quantity" field.
func (u *PaperPositionUpsertOne) SetTokenQuantity(v string) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetTokenQuantity(v)
	})
}

// UpdateTokenQuantity sets the "token_quantity" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateTokenQuantity() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateTokenQuantity()
	})
}

// ClearTokenQuantity clears the value of the "token_quantity" field.
func (u *PaperPositionUpsertOne) ClearTokenQuantity() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearTokenQuantity()
	})
}

// SetOpenedAt sets the "opened_at" field.
func (u *PaperPositionUpsertOne) SetOpenedAt(v time.Time) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetOpenedAt(v)
	})
}

// UpdateOpenedAt sets the "opened_at" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateOpenedAt() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateOpenedAt()
	})
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (u *PaperPositionUpsertOne) ClearOpenedAt() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearOpenedAt()
	})
}

// SetClosedAt sets the "closed_at" field.
func (u *PaperPositionUpsertOne) SetClosedAt(v time.Time) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetClosedAt(v)
	})
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateClosedAt() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateClosedAt()
	})
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *PaperPositionUpsertOne) ClearClosedAt() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearClosedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaperPositionUpsertOne) SetUpdatedAt(v time.Time) *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaperPositionUpsertOne) UpdateUpdatedAt() *PaperPositionUpsertOne {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaperPositionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaperPositionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaperPositionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaperPositionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaperPositionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaperPositionCreateBulk is the builder for creating many PaperPosition entities in bulk.
type PaperPositionCreateBulk struct {
	config
	err      error
	builders []*PaperPositionCreate
	conflict []sql.ConflictOption
}

// Save creates the PaperPosition entities in the database.
func (_c *PaperPositionCreateBulk) Save(ctx context.Context) ([]*PaperPosition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaperPosition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaperPositionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaperPositionCreateBulk) SaveX(ctx context.Context) []*PaperPosition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaperPositionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaperPositionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaperPosition.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaperPositionUpsert) {
//			SetState(v+v).
//		}).
//		Exec(ctx)
func (_c *PaperPositionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaperPositionUpsertBulk {
	_c.conflict = opts
	return &PaperPositionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaperPosition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaperPositionCreateBulk) OnConflictColumns(columns ...string) *PaperPositionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaperPositionUpsertBulk{
		create: _c,
	}
}

// PaperPositionUpsertBulk is the builder for "upsert"-ing
// a bulk of PaperPosition nodes.
type PaperPositionUpsertBulk struct {
	create *PaperPositionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaperPosition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaperPositionUpsertBulk) UpdateNewValues() *PaperPositionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paperposition.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaperPosition.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaperPositionUpsertBulk) Ignore() *PaperPositionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaperPositionUpsertBulk) DoNothing() *PaperPositionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaperPositionCreateBulk.OnConflict
// documentation for more info.
func (u *PaperPositionUpsertBulk) Update(set func(*PaperPositionUpsert)) *PaperPositionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaperPositionUpsert{UpdateSet: update})
	}))
	return u
}

// SetState sets the "state" field.
func (u *PaperPositionUpsertBulk) SetState(v paperposition.State) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateState() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateState()
	})
}

// SetNotionalMicros sets the "notional_micros" field.
func (u *PaperPositionUpsertBulk) SetNotionalMicros(v int64) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetNotionalMicros(v)
	})
}

// AddNotionalMicros adds v to the "notional_micros" field.
func (u *PaperPositionUpsertBulk) AddNotionalMicros(v int64) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.AddNotionalMicros(v)
	})
}

// UpdateNotionalMicros sets the "notional_micros" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateNotionalMicros() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateNotionalMicros()
	})
}

// SetStrategyVersion sets the "strategy_version" field.
func (u *PaperPositionUpsertBulk) SetStrategyVersion(v string) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetStrategyVersion(v)
	})
}

// UpdateStrategyVersion sets the "strategy_version" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateStrategyVersion() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateStrategyVersion()
	})
}

// SetNoRouteCount sets the "no_route_count" field.
func (u *PaperPositionUpsertBulk) SetNoRouteCount(v int) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetNoRouteCount(v)
	})
}

// AddNoRouteCount adds v to the "no_route_count" field.
func (u *PaperPositionUpsertBulk) AddNoRouteCount(v int) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.AddNoRouteCount(v)
	})
}

// UpdateNoRouteCount sets the "no_route_count" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateNoRouteCount() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateNoRouteCount()
	})
}

// SetQuoteMint sets the "quote_mint" field.
func (u *PaperPositionUpsertBulk) SetQuoteMint(v string) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetQuoteMint(v)
	})
}

// UpdateQuoteMint sets the "quote_mint" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateQuoteMint() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateQuoteMint()
	})
}

// ClearQuoteMint clears the value of the "quote_mint" field.
func (u *PaperPositionUpsertBulk) ClearQuoteMint() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearQuoteMint()
	})
}

// SetMintAddress sets the "mint_address" field.
func (u *PaperPositionUpsertBulk) SetMintAddress(v string) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetMintAddress(v)
	})
}

// UpdateMintAddress sets the "mint_address" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateMintAddress() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateMintAddress()
	})
}

// ClearMintAddress clears the value of the "mint_address" field.
func (u *PaperPositionUpsertBulk) ClearMintAddress() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearMintAddress()
	})
}

// SetEntryPrice sets the "entry_price" field.
func (u *PaperPositionUpsertBulk) SetEntryPrice(v string) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetEntryPrice(v)
	})
}

// UpdateEntryPrice sets the "entry_price" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateEntryPrice() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateEntryPrice()
	})
}

// ClearEntryPrice clears the value of the "entry_price" field.
func (u *PaperPositionUpsertBulk) ClearEntryPrice() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearEntryPrice()
	})
}

// SetEntryInputAmount sets the "entry_input_amount" field.
func (u *PaperPositionUpsertBulk) SetEntryInputAmount(v string) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetEntryInputAmount(v)
	})
}

// UpdateEntryInputAmount sets the "entry_input_amount" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateEntryInputAmount() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateEntryInputAmount()
	})
}

// ClearEntryInputAmount clears the value of the "entry_input_amount" field.
func (u *PaperPositionUpsertBulk) ClearEntryInputAmount() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearEntryInputAmount()
	})
}

// SetEntryNetworkFeeMicros sets the "entry_network_fee_micros" field.
func (u *PaperPositionUpsertBulk) SetEntryNetworkFeeMicros(v int64) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetEntryNetworkFeeMicros(v)
	})
}

// AddEntryNetworkFeeMicros adds v to the "entry_network_fee_micros" field.
func (u *PaperPositionUpsertBulk) AddEntryNetworkFeeMicros(v int64) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.AddEntryNetworkFeeMicros(v)
	})
}

// UpdateEntryNetworkFeeMicros sets the "entry_network_fee_micros" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateEntryNetworkFeeMicros() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateEntryNetworkFeeMicros()
	})
}

// ClearEntryNetworkFeeMicros clears the value of the "entry_network_fee_micros" field.
func (u *PaperPositionUpsertBulk) ClearEntryNetworkFeeMicros() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearEntryNetworkFeeMicros()
	})
}

// SetEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field.
func (u *PaperPositionUpsertBulk) SetEntryPriorityFeeMicros(v int64) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetEntryPriorityFeeMicros(v)
	})
}

// AddEntryPriorityFeeMicros adds v to the "entry_priority_fee_micros" field.
func (u *PaperPositionUpsertBulk) AddEntryPriorityFeeMicros(v int64) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.AddEntryPriorityFeeMicros(v)
	})
}

// UpdateEntryPriorityFeeMicros sets the "entry_priority_fee_micros" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateEntryPriorityFeeMicros() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateEntryPriorityFeeMicros()
	})
}

// ClearEntryPriorityFeeMicros clears the value of the "entry_priority_fee_micros" field.
func (u *PaperPositionUpsertBulk) ClearEntryPriorityFeeMicros() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearEntryPriorityFeeMicros()
	})
}

// SetTokenQuantity sets the "token_quantity" field.
func (u *PaperPositionUpsertBulk) SetTokenQuantity(v string) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetTokenQuantity(v)
	})
}

// UpdateTokenQuantity sets the "token_quantity" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateTokenQuantity() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateTokenQuantity()
	})
}

// ClearTokenQuantity clears the value of the "token_quantity" field.
func (u *PaperPositionUpsertBulk) ClearTokenQuantity() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearTokenQuantity()
	})
}

// SetOpenedAt sets the "opened_at" field.
func (u *PaperPositionUpsertBulk) SetOpenedAt(v time.Time) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetOpenedAt(v)
	})
}

// UpdateOpenedAt sets the "opened_at" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateOpenedAt() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateOpenedAt()
	})
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (u *PaperPositionUpsertBulk) ClearOpenedAt() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearOpenedAt()
	})
}

// SetClosedAt sets the "closed_at" field.
func (u *PaperPositionUpsertBulk) SetClosedAt(v time.Time) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetClosedAt(v)
	})
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateClosedAt() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateClosedAt()
	})
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *PaperPositionUpsertBulk) ClearClosedAt() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.ClearClosedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaperPositionUpsertBulk) SetUpdatedAt(v time.Time) *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaperPositionUpsertBulk) UpdateUpdatedAt() *PaperPositionUpsertBulk {
	return u.Update(func(s *PaperPositionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaperPositionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaperPositionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaperPositionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaperPositionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
