// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/positionevent"
)

// PositionEvent is the model entity for the PositionEvent schema.
type PositionEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Details holds the value of the "details" field.
	Details map[string]interface{} `json:"details,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PositionEventQuery when eager-loading is set.
	Edges                 PositionEventEdges `json:"edges"`
	paper_position_events *int
	selectValues          sql.SelectValues
}

// PositionEventEdges holds the relations/edges for other nodes in the graph.
type PositionEventEdges struct {
	// Position holds the value of the position edge.
	Position *PaperPosition `json:"position,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PositionOrErr returns the Position value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PositionEventEdges) PositionOrErr() (*PaperPosition, error) {
	if e.Position != nil {
		return e.Position, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: paperposition.Label}
	}
	return nil, &NotLoadedError{edge: "position"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PositionEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case positionevent.FieldDetails:
			values[i] = new([]byte)
		case positionevent.FieldID:
			values[i] = new(sql.NullInt64)
		case positionevent.FieldEventType:
			values[i] = new(sql.NullString)
		case positionevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case positionevent.ForeignKeys[0]: // paper_position_events
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PositionEvent fields.
func (_m *PositionEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case positionevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case positionevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case positionevent.FieldDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Details); err != nil {
					return fmt.Errorf("unmarshal field details: %w", err)
				}
			}
		case positionevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case positionevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field paper_position_events", value)
			} else if value.Valid {
				_m.paper_position_events = new(int)
				*_m.paper_position_events = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PositionEvent.
// This includes values selected through modifiers, order, etc.
func (_m *PositionEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPosition queries the "position" edge of the PositionEvent entity.
func (_m *PositionEvent) QueryPosition() *PaperPositionQuery {
	return NewPositionEventClient(_m.config).QueryPosition(_m)
}

// Update returns a builder for updating this PositionEvent.
// Note that you need to call PositionEvent.Unwrap() before calling this method if this PositionEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PositionEvent) Update() *PositionEventUpdateOne {
	return NewPositionEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PositionEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PositionEvent) Unwrap() *PositionEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PositionEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PositionEvent) String() string {
	var builder strings.Builder
	builder.WriteString("PositionEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(fmt.Sprintf("%v", _m.Details))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PositionEvents is a parsable slice of PositionEvent.
type PositionEvents []*PositionEvent
