// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/positionevent"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
)

// PositionEventUpdate is the builder for updating PositionEvent entities.
type PositionEventUpdate struct {
	config
	hooks    []Hook
	mutation *PositionEventMutation
}

// Where appends a list predicates to the PositionEventUpdate builder.
func (_u *PositionEventUpdate) Where(ps ...predicate.PositionEvent) *PositionEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *PositionEventUpdate) SetEventType(v string) *PositionEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *PositionEventUpdate) SetNillableEventType(v *string) *PositionEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *PositionEventUpdate) SetDetails(v map[string]interface{}) *PositionEventUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// SetPositionID sets the "position" edge to the PaperPosition entity by ID.
func (_u *PositionEventUpdate) SetPositionID(id int) *PositionEventUpdate {
	_u.mutation.SetPositionID(id)
	return _u
}

// SetPosition sets the "position" edge to the PaperPosition entity.
func (_u *PositionEventUpdate) SetPosition(v *PaperPosition) *PositionEventUpdate {
	return _u.SetPositionID(v.ID)
}

// Mutation returns the PositionEventMutation object of the builder.
func (_u *PositionEventUpdate) Mutation() *PositionEventMutation {
	return _u.mutation
}

// ClearPosition clears the "position" edge to the PaperPosition entity.
func (_u *PositionEventUpdate) ClearPosition() *PositionEventUpdate {
	_u.mutation.ClearPosition()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PositionEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PositionEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PositionEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PositionEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PositionEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := positionevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "PositionEvent.event_type": %w`, err)}
		}
	}
	if _u.mutation.PositionCleared() && len(_u.mutation.PositionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PositionEvent.position"`)
	}
	return nil
}

func (_u *PositionEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(positionevent.Table, positionevent.Columns, sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(positionevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(positionevent.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionevent.PositionTable,
			Columns: []string{positionevent.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionevent.PositionTable,
			Columns: []string{positionevent.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{positionevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PositionEventUpdateOne is the builder for updating a single PositionEvent entity.
type PositionEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PositionEventMutation
}

// SetEventType sets the "event_type" field.
func (_u *PositionEventUpdateOne) SetEventType(v string) *PositionEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *PositionEventUpdateOne) SetNillableEventType(v *string) *PositionEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *PositionEventUpdateOne) SetDetails(v map[string]interface{}) *PositionEventUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// SetPositionID sets the "position" edge to the PaperPosition entity by ID.
func (_u *PositionEventUpdateOne) SetPositionID(id int) *PositionEventUpdateOne {
	_u.mutation.SetPositionID(id)
	return _u
}

// SetPosition sets the "position" edge to the PaperPosition entity.
func (_u *PositionEventUpdateOne) SetPosition(v *PaperPosition) *PositionEventUpdateOne {
	return _u.SetPositionID(v.ID)
}

// Mutation returns the PositionEventMutation object of the builder.
func (_u *PositionEventUpdateOne) Mutation() *PositionEventMutation {
	return _u.mutation
}

// ClearPosition clears the "position" edge to the PaperPosition entity.
func (_u *PositionEventUpdateOne) ClearPosition() *PositionEventUpdateOne {
	_u.mutation.ClearPosition()
	return _u
}

// Where appends a list predicates to the PositionEventUpdate builder.
func (_u *PositionEventUpdateOne) Where(ps ...predicate.PositionEvent) *PositionEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PositionEventUpdateOne) Select(field string, fields ...string) *PositionEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PositionEvent entity.
func (_u *PositionEventUpdateOne) Save(ctx context.Context) (*PositionEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PositionEventUpdateOne) SaveX(ctx context.Context) *PositionEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PositionEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PositionEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PositionEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := positionevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "PositionEvent.event_type": %w`, err)}
		}
	}
	if _u.mutation.PositionCleared() && len(_u.mutation.PositionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PositionEvent.position"`)
	}
	return nil
}

func (_u *PositionEventUpdateOne) sqlSave(ctx context.Context) (_node *PositionEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(positionevent.Table, positionevent.Columns, sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PositionEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, positionevent.FieldID)
		for _, f := range fields {
			if !positionevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != positionevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(positionevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(positionevent.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionevent.PositionTable,
			Columns: []string{positionevent.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionevent.PositionTable,
			Columns: []string{positionevent.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PositionEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{positionevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
