// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/apiusage"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/botstate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidatesnapshot"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/dailyresult"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/positionevent"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/positionmark"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/schema"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/socialsnapshot"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/tradedecision"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/verdict"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apiusageFields := schema.APIUsage{}.Fields()
	_ = apiusageFields
	// apiusageDescProvider is the schema descriptor for provider field.
	apiusageDescProvider := apiusageFields[0].Descriptor()
	// apiusage.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	apiusage.ProviderValidator = apiusageDescProvider.Validators[0].(func(string) error)
	// apiusageDescRequestCount is the schema descriptor for request_count field.
	apiusageDescRequestCount := apiusageFields[2].Descriptor()
	// apiusage.RequestCountValidator is a validator for the "request_count" field. It is called by the builders before save.
	apiusage.RequestCountValidator = apiusageDescRequestCount.Validators[0].(func(int) error)
	// apiusageDescFailureCount is the schema descriptor for failure_count field.
	apiusageDescFailureCount := apiusageFields[3].Descriptor()
	// apiusage.FailureCountValidator is a validator for the "failure_count" field. It is called by the builders before save.
	apiusage.FailureCountValidator = apiusageDescFailureCount.Validators[0].(func(int) error)
	// apiusageDescCreatedAt is the schema descriptor for created_at field.
	apiusageDescCreatedAt := apiusageFields[4].Descriptor()
	// apiusage.DefaultCreatedAt holds the default value on creation for the created_at field.
	apiusage.DefaultCreatedAt = apiusageDescCreatedAt.Default.(func() time.Time)
	// apiusageDescUpdatedAt is the schema descriptor for updated_at field.
	apiusageDescUpdatedAt := apiusageFields[5].Descriptor()
	// apiusage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apiusage.DefaultUpdatedAt = apiusageDescUpdatedAt.Default.(func() time.Time)
	// apiusage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apiusage.UpdateDefaultUpdatedAt = apiusageDescUpdatedAt.UpdateDefault.(func() time.Time)
	botstateFields := schema.BotState{}.Fields()
	_ = botstateFields
	// botstateDescStateKey is the schema descriptor for state_key field.
	botstateDescStateKey := botstateFields[0].Descriptor()
	// botstate.StateKeyValidator is a validator for the "state_key" field. It is called by the builders before save.
	botstate.StateKeyValidator = botstateDescStateKey.Validators[0].(func(string) error)
	// botstateDescCreatedAt is the schema descriptor for created_at field.
	botstateDescCreatedAt := botstateFields[2].Descriptor()
	// botstate.DefaultCreatedAt holds the default value on creation for the created_at field.
	botstate.DefaultCreatedAt = botstateDescCreatedAt.Default.(func() time.Time)
	// botstateDescUpdatedAt is the schema descriptor for updated_at field.
	botstateDescUpdatedAt := botstateFields[3].Descriptor()
	// botstate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	botstate.DefaultUpdatedAt = botstateDescUpdatedAt.Default.(func() time.Time)
	// botstate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	botstate.UpdateDefaultUpdatedAt = botstateDescUpdatedAt.UpdateDefault.(func() time.Time)
	candidateFields := schema.Candidate{}.Fields()
	_ = candidateFields
	// candidateDescNetwork is the schema descriptor for network field.
	candidateDescNetwork := candidateFields[0].Descriptor()
	// candidate.NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	candidate.NetworkValidator = candidateDescNetwork.Validators[0].(func(string) error)
	// candidateDescMintAddress is the schema descriptor for mint_address field.
	candidateDescMintAddress := candidateFields[1].Descriptor()
	// candidate.MintAddressValidator is a validator for the "mint_address" field. It is called by the builders before save.
	candidate.MintAddressValidator = candidateDescMintAddress.Validators[0].(func(string) error)
	// candidateDescPoolAddress is the schema descriptor for pool_address field.
	candidateDescPoolAddress := candidateFields[2].Descriptor()
	// candidate.PoolAddressValidator is a validator for the "pool_address" field. It is called by the builders before save.
	candidate.PoolAddressValidator = candidateDescPoolAddress.Validators[0].(func(string) error)
	// candidateDescDiscoveredAt is the schema descriptor for discovered_at field.
	candidateDescDiscoveredAt := candidateFields[3].Descriptor()
	// candidate.DefaultDiscoveredAt holds the default value on creation for the discovered_at field.
	candidate.DefaultDiscoveredAt = candidateDescDiscoveredAt.Default.(func() time.Time)
	// candidateDescCreatedAt is the schema descriptor for created_at field.
	candidateDescCreatedAt := candidateFields[4].Descriptor()
	// candidate.DefaultCreatedAt holds the default value on creation for the created_at field.
	candidate.DefaultCreatedAt = candidateDescCreatedAt.Default.(func() time.Time)
	// candidateDescUpdatedAt is the schema descriptor for updated_at field.
	candidateDescUpdatedAt := candidateFields[5].Descriptor()
	// candidate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	candidate.DefaultUpdatedAt = candidateDescUpdatedAt.Default.(func() time.Time)
	// candidate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	candidate.UpdateDefaultUpdatedAt = candidateDescUpdatedAt.UpdateDefault.(func() time.Time)
	candidatesnapshotFields := schema.CandidateSnapshot{}.Fields()
	_ = candidatesnapshotFields
	// candidatesnapshotDescObservedAt is the schema descriptor for observed_at field.
	candidatesnapshotDescObservedAt := candidatesnapshotFields[1].Descriptor()
	// candidatesnapshot.DefaultObservedAt holds the default value on creation for the observed_at field.
	candidatesnapshot.DefaultObservedAt = candidatesnapshotDescObservedAt.Default.(func() time.Time)
	// candidatesnapshotDescCreatedAt is the schema descriptor for created_at field.
	candidatesnapshotDescCreatedAt := candidatesnapshotFields[2].Descriptor()
	// candidatesnapshot.DefaultCreatedAt holds the default value on creation for the created_at field.
	candidatesnapshot.DefaultCreatedAt = candidatesnapshotDescCreatedAt.Default.(func() time.Time)
	dailyresultFields := schema.DailyResult{}.Fields()
	_ = dailyresultFields
	// dailyresultDescStrategyVersion is the schema descriptor for strategy_version field.
	dailyresultDescStrategyVersion := dailyresultFields[1].Descriptor()
	// dailyresult.StrategyVersionValidator is a validator for the "strategy_version" field. It is called by the builders before save.
	dailyresult.StrategyVersionValidator = dailyresultDescStrategyVersion.Validators[0].(func(string) error)
	// dailyresultDescDailyAdmittedCount is the schema descriptor for daily_admitted_count field.
	dailyresultDescDailyAdmittedCount := dailyresultFields[2].Descriptor()
	// dailyresult.DailyAdmittedCountValidator is a validator for the "daily_admitted_count" field. It is called by the builders before save.
	dailyresult.DailyAdmittedCountValidator = func() func(int) error {
		validators := dailyresultDescDailyAdmittedCount.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(daily_admitted_count int) error {
			for _, fn := range fns {
				if err := fn(daily_admitted_count); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dailyresultDescRealizedPnlMicros is the schema descriptor for realized_pnl_micros field.
	dailyresultDescRealizedPnlMicros := dailyresultFields[3].Descriptor()
	// dailyresult.DefaultRealizedPnlMicros holds the default value on creation for the realized_pnl_micros field.
	dailyresult.DefaultRealizedPnlMicros = dailyresultDescRealizedPnlMicros.Default.(int64)
	// dailyresultDescCreatedAt is the schema descriptor for created_at field.
	dailyresultDescCreatedAt := dailyresultFields[4].Descriptor()
	// dailyresult.DefaultCreatedAt holds the default value on creation for the created_at field.
	dailyresult.DefaultCreatedAt = dailyresultDescCreatedAt.Default.(func() time.Time)
	// dailyresultDescUpdatedAt is the schema descriptor for updated_at field.
	dailyresultDescUpdatedAt := dailyresultFields[5].Descriptor()
	// dailyresult.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dailyresult.DefaultUpdatedAt = dailyresultDescUpdatedAt.Default.(func() time.Time)
	// dailyresult.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dailyresult.UpdateDefaultUpdatedAt = dailyresultDescUpdatedAt.UpdateDefault.(func() time.Time)
	paperpositionFields := schema.PaperPosition{}.Fields()
	_ = paperpositionFields
	// paperpositionDescNotionalMicros is the schema descriptor for notional_micros field.
	paperpositionDescNotionalMicros := paperpositionFields[1].Descriptor()
	// paperposition.NotionalMicrosValidator is a validator for the "notional_micros" field. It is called by the builders before save.
	paperposition.NotionalMicrosValidator = paperpositionDescNotionalMicros.Validators[0].(func(int64) error)
	// paperpositionDescStrategyVersion is the schema descriptor for strategy_version field.
	paperpositionDescStrategyVersion := paperpositionFields[2].Descriptor()
	// paperposition.DefaultStrategyVersion holds the default value on creation for the strategy_version field.
	paperposition.DefaultStrategyVersion = paperpositionDescStrategyVersion.Default.(string)
	// paperposition.StrategyVersionValidator is a validator for the "strategy_version" field. It is called by the builders before save.
	paperposition.StrategyVersionValidator = paperpositionDescStrategyVersion.Validators[0].(func(string) error)
	// paperpositionDescNoRouteCount is the schema descriptor for no_route_count field.
	paperpositionDescNoRouteCount := paperpositionFields[3].Descriptor()
	// paperposition.DefaultNoRouteCount holds the default value on creation for the no_route_count field.
	paperposition.DefaultNoRouteCount = paperpositionDescNoRouteCount.Default.(int)
	// paperposition.NoRouteCountValidator is a validator for the "no_route_count" field. It is called by the builders before save.
	paperposition.NoRouteCountValidator = paperpositionDescNoRouteCount.Validators[0].(func(int) error)
	// paperpositionDescCreatedAt is the schema descriptor for created_at field.
	paperpositionDescCreatedAt := paperpositionFields[13].Descriptor()
	// paperposition.DefaultCreatedAt holds the default value on creation for the created_at field.
	paperposition.DefaultCreatedAt = paperpositionDescCreatedAt.Default.(func() time.Time)
	// paperpositionDescUpdatedAt is the schema descriptor for updated_at field.
	paperpositionDescUpdatedAt := paperpositionFields[14].Descriptor()
	// paperposition.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paperposition.DefaultUpdatedAt = paperpositionDescUpdatedAt.Default.(func() time.Time)
	// paperposition.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paperposition.UpdateDefaultUpdatedAt = paperpositionDescUpdatedAt.UpdateDefault.(func() time.Time)
	positioneventFields := schema.PositionEvent{}.Fields()
	_ = positioneventFields
	// positioneventDescEventType is the schema descriptor for event_type field.
	positioneventDescEventType := positioneventFields[0].Descriptor()
	// positionevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	positionevent.EventTypeValidator = positioneventDescEventType.Validators[0].(func(string) error)
	// positioneventDescCreatedAt is the schema descriptor for created_at field.
	positioneventDescCreatedAt := positioneventFields[2].Descriptor()
	// positionevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	positionevent.DefaultCreatedAt = positioneventDescCreatedAt.Default.(func() time.Time)
	positionmarkFields := schema.PositionMark{}.Fields()
	_ = positionmarkFields
	// positionmarkDescPrice is the schema descriptor for price field.
	positionmarkDescPrice := positionmarkFields[0].Descriptor()
	// positionmark.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	positionmark.PriceValidator = positionmarkDescPrice.Validators[0].(func(string) error)
	// positionmarkDescFeeEstimate is the schema descriptor for fee_estimate field.
	positionmarkDescFeeEstimate := positionmarkFields[2].Descriptor()
	// positionmark.FeeEstimateValidator is a validator for the "fee_estimate" field. It is called by the builders before save.
	positionmark.FeeEstimateValidator = positionmarkDescFeeEstimate.Validators[0].(func(int64) error)
	// positionmarkDescNoRouteCount is the schema descriptor for no_route_count field.
	positionmarkDescNoRouteCount := positionmarkFields[8].Descriptor()
	// positionmark.DefaultNoRouteCount holds the default value on creation for the no_route_count field.
	positionmark.DefaultNoRouteCount = positionmarkDescNoRouteCount.Default.(int)
	// positionmark.NoRouteCountValidator is a validator for the "no_route_count" field. It is called by the builders before save.
	positionmark.NoRouteCountValidator = positionmarkDescNoRouteCount.Validators[0].(func(int) error)
	// positionmarkDescObservedAt is the schema descriptor for observed_at field.
	positionmarkDescObservedAt := positionmarkFields[9].Descriptor()
	// positionmark.DefaultObservedAt holds the default value on creation for the observed_at field.
	positionmark.DefaultObservedAt = positionmarkDescObservedAt.Default.(func() time.Time)
	// positionmarkDescCreatedAt is the schema descriptor for created_at field.
	positionmarkDescCreatedAt := positionmarkFields[10].Descriptor()
	// positionmark.DefaultCreatedAt holds the default value on creation for the created_at field.
	positionmark.DefaultCreatedAt = positionmarkDescCreatedAt.Default.(func() time.Time)
	socialsnapshotFields := schema.SocialSnapshot{}.Fields()
	_ = socialsnapshotFields
	// socialsnapshotDescObservedAt is the schema descriptor for observed_at field.
	socialsnapshotDescObservedAt := socialsnapshotFields[2].Descriptor()
	// socialsnapshot.DefaultObservedAt holds the default value on creation for the observed_at field.
	socialsnapshot.DefaultObservedAt = socialsnapshotDescObservedAt.Default.(func() time.Time)
	// socialsnapshotDescCreatedAt is the schema descriptor for created_at field.
	socialsnapshotDescCreatedAt := socialsnapshotFields[3].Descriptor()
	// socialsnapshot.DefaultCreatedAt holds the default value on creation for the created_at field.
	socialsnapshot.DefaultCreatedAt = socialsnapshotDescCreatedAt.Default.(func() time.Time)
	tradedecisionFields := schema.TradeDecision{}.Fields()
	_ = tradedecisionFields
	// tradedecisionDescIdempotencyKey is the schema descriptor for idempotency_key field.
	tradedecisionDescIdempotencyKey := tradedecisionFields[0].Descriptor()
	// tradedecision.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	tradedecision.IdempotencyKeyValidator = tradedecisionDescIdempotencyKey.Validators[0].(func(string) error)
	// tradedecisionDescOutcome is the schema descriptor for outcome field.
	tradedecisionDescOutcome := tradedecisionFields[1].Descriptor()
	// tradedecision.OutcomeValidator is a validator for the "outcome" field. It is called by the builders before save.
	tradedecision.OutcomeValidator = tradedecisionDescOutcome.Validators[0].(func(string) error)
	// tradedecisionDescCreatedAt is the schema descriptor for created_at field.
	tradedecisionDescCreatedAt := tradedecisionFields[3].Descriptor()
	// tradedecision.DefaultCreatedAt holds the default value on creation for the created_at field.
	tradedecision.DefaultCreatedAt = tradedecisionDescCreatedAt.Default.(func() time.Time)
	verdictFields := schema.Verdict{}.Fields()
	_ = verdictFields
	// verdictDescProvider is the schema descriptor for provider field.
	verdictDescProvider := verdictFields[0].Descriptor()
	// verdict.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	verdict.ProviderValidator = verdictDescProvider.Validators[0].(func(string) error)
	// verdictDescModel is the schema descriptor for model field.
	verdictDescModel := verdictFields[1].Descriptor()
	// verdict.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	verdict.ModelValidator = verdictDescModel.Validators[0].(func(string) error)
	// verdictDescOutcome is the schema descriptor for outcome field.
	verdictDescOutcome := verdictFields[2].Descriptor()
	// verdict.OutcomeValidator is a validator for the "outcome" field. It is called by the builders before save.
	verdict.OutcomeValidator = verdictDescOutcome.Validators[0].(func(string) error)
	// verdictDescCreatedAt is the schema descriptor for created_at field.
	verdictDescCreatedAt := verdictFields[4].Descriptor()
	// verdict.DefaultCreatedAt holds the default value on creation for the created_at field.
	verdict.DefaultCreatedAt = verdictDescCreatedAt.Default.(func() time.Time)
}
