// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/socialsnapshot"
)

// SocialSnapshotUpdate is the builder for updating SocialSnapshot entities.
type SocialSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *SocialSnapshotMutation
}

// Where appends a list predicates to the SocialSnapshotUpdate builder.
func (_u *SocialSnapshotUpdate) Where(ps ...predicate.SocialSnapshot) *SocialSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSocialEvidence sets the "social_evidence" field.
func (_u *SocialSnapshotUpdate) SetSocialEvidence(v map[string]interface{}) *SocialSnapshotUpdate {
	_u.mutation.SetSocialEvidence(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *SocialSnapshotUpdate) SetScore(v int) *SocialSnapshotUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *SocialSnapshotUpdate) SetNillableScore(v *int) *SocialSnapshotUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *SocialSnapshotUpdate) AddScore(v int) *SocialSnapshotUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *SocialSnapshotUpdate) SetObservedAt(v time.Time) *SocialSnapshotUpdate {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *SocialSnapshotUpdate) SetNillableObservedAt(v *time.Time) *SocialSnapshotUpdate {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_u *SocialSnapshotUpdate) SetCandidateID(id int) *SocialSnapshotUpdate {
	_u.mutation.SetCandidateID(id)
	return _u
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_u *SocialSnapshotUpdate) SetCandidate(v *Candidate) *SocialSnapshotUpdate {
	return _u.SetCandidateID(v.ID)
}

// Mutation returns the SocialSnapshotMutation object of the builder.
func (_u *SocialSnapshotUpdate) Mutation() *SocialSnapshotMutation {
	return _u.mutation
}

// ClearCandidate clears the "candidate" edge to the Candidate entity.
func (_u *SocialSnapshotUpdate) ClearCandidate() *SocialSnapshotUpdate {
	_u.mutation.ClearCandidate()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SocialSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SocialSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SocialSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SocialSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SocialSnapshotUpdate) check() error {
	if _u.mutation.CandidateCleared() && len(_u.mutation.CandidateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SocialSnapshot.candidate"`)
	}
	return nil
}

func (_u *SocialSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(socialsnapshot.Table, socialsnapshot.Columns, sqlgraph.NewFieldSpec(socialsnapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SocialEvidence(); ok {
		_spec.SetField(socialsnapshot.FieldSocialEvidence, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(socialsnapshot.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(socialsnapshot.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(socialsnapshot.FieldObservedAt, field.TypeTime, value)
	}
	if _u.mutation.CandidateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialsnapshot.CandidateTable,
			Columns: []string{socialsnapshot.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialsnapshot.CandidateTable,
			Columns: []string{socialsnapshot.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{socialsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SocialSnapshotUpdateOne is the builder for updating a single SocialSnapshot entity.
type SocialSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SocialSnapshotMutation
}

// SetSocialEvidence sets the "social_evidence" field.
func (_u *SocialSnapshotUpdateOne) SetSocialEvidence(v map[string]interface{}) *SocialSnapshotUpdateOne {
	_u.mutation.SetSocialEvidence(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *SocialSnapshotUpdateOne) SetScore(v int) *SocialSnapshotUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *SocialSnapshotUpdateOne) SetNillableScore(v *int) *SocialSnapshotUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *SocialSnapshotUpdateOne) AddScore(v int) *SocialSnapshotUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *SocialSnapshotUpdateOne) SetObservedAt(v time.Time) *SocialSnapshotUpdateOne {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *SocialSnapshotUpdateOne) SetNillableObservedAt(v *time.Time) *SocialSnapshotUpdateOne {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_u *SocialSnapshotUpdateOne) SetCandidateID(id int) *SocialSnapshotUpdateOne {
	_u.mutation.SetCandidateID(id)
	return _u
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_u *SocialSnapshotUpdateOne) SetCandidate(v *Candidate) *SocialSnapshotUpdateOne {
	return _u.SetCandidateID(v.ID)
}

// Mutation returns the SocialSnapshotMutation object of the builder.
func (_u *SocialSnapshotUpdateOne) Mutation() *SocialSnapshotMutation {
	return _u.mutation
}

// ClearCandidate clears the "candidate" edge to the Candidate entity.
func (_u *SocialSnapshotUpdateOne) ClearCandidate() *SocialSnapshotUpdateOne {
	_u.mutation.ClearCandidate()
	return _u
}

// Where appends a list predicates to the SocialSnapshotUpdate builder.
func (_u *SocialSnapshotUpdateOne) Where(ps ...predicate.SocialSnapshot) *SocialSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SocialSnapshotUpdateOne) Select(field string, fields ...string) *SocialSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SocialSnapshot entity.
func (_u *SocialSnapshotUpdateOne) Save(ctx context.Context) (*SocialSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SocialSnapshotUpdateOne) SaveX(ctx context.Context) *SocialSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SocialSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SocialSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SocialSnapshotUpdateOne) check() error {
	if _u.mutation.CandidateCleared() && len(_u.mutation.CandidateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SocialSnapshot.candidate"`)
	}
	return nil
}

func (_u *SocialSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *SocialSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(socialsnapshot.Table, socialsnapshot.Columns, sqlgraph.NewFieldSpec(socialsnapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SocialSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, socialsnapshot.FieldID)
		for _, f := range fields {
			if !socialsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != socialsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SocialEvidence(); ok {
		_spec.SetField(socialsnapshot.FieldSocialEvidence, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(socialsnapshot.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(socialsnapshot.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(socialsnapshot.FieldObservedAt, field.TypeTime, value)
	}
	if _u.mutation.CandidateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialsnapshot.CandidateTable,
			Columns: []string{socialsnapshot.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialsnapshot.CandidateTable,
			Columns: []string{socialsnapshot.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SocialSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{socialsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
