// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/socialsnapshot"
)

// SocialSnapshotDelete is the builder for deleting a SocialSnapshot entity.
type SocialSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *SocialSnapshotMutation
}

// Where appends a list predicates to the SocialSnapshotDelete builder.
func (_d *SocialSnapshotDelete) Where(ps ...predicate.SocialSnapshot) *SocialSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SocialSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SocialSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SocialSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(socialsnapshot.Table, sqlgraph.NewFieldSpec(socialsnapshot.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SocialSnapshotDeleteOne is the builder for deleting a single SocialSnapshot entity.
type SocialSnapshotDeleteOne struct {
	_d *SocialSnapshotDelete
}

// Where appends a list predicates to the SocialSnapshotDelete builder.
func (_d *SocialSnapshotDeleteOne) Where(ps ...predicate.SocialSnapshot) *SocialSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SocialSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{socialsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SocialSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
