// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/tradedecision"
)

// TradeDecisionUpdate is the builder for updating TradeDecision entities.
type TradeDecisionUpdate struct {
	config
	hooks    []Hook
	mutation *TradeDecisionMutation
}

// Where appends a list predicates to the TradeDecisionUpdate builder.
func (_u *TradeDecisionUpdate) Where(ps ...predicate.TradeDecision) *TradeDecisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *TradeDecisionUpdate) SetIdempotencyKey(v string) *TradeDecisionUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *TradeDecisionUpdate) SetNillableIdempotencyKey(v *string) *TradeDecisionUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *TradeDecisionUpdate) SetOutcome(v string) *TradeDecisionUpdate {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *TradeDecisionUpdate) SetNillableOutcome(v *string) *TradeDecisionUpdate {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetRuleResults sets the "rule_results" field.
func (_u *TradeDecisionUpdate) SetRuleResults(v map[string]interface{}) *TradeDecisionUpdate {
	_u.mutation.SetRuleResults(v)
	return _u
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_u *TradeDecisionUpdate) SetCandidateID(id int) *TradeDecisionUpdate {
	_u.mutation.SetCandidateID(id)
	return _u
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_u *TradeDecisionUpdate) SetCandidate(v *Candidate) *TradeDecisionUpdate {
	return _u.SetCandidateID(v.ID)
}

// SetPositionID sets the "position" edge to the PaperPosition entity by ID.
func (_u *TradeDecisionUpdate) SetPositionID(id int) *TradeDecisionUpdate {
	_u.mutation.SetPositionID(id)
	return _u
}

// SetNillablePositionID sets the "position" edge to the PaperPosition entity by ID if the given value is not nil.
func (_u *TradeDecisionUpdate) SetNillablePositionID(id *int) *TradeDecisionUpdate {
	if id != nil {
		_u = _u.SetPositionID(*id)
	}
	return _u
}

// SetPosition sets the "position" edge to the PaperPosition entity.
func (_u *TradeDecisionUpdate) SetPosition(v *PaperPosition) *TradeDecisionUpdate {
	return _u.SetPositionID(v.ID)
}

// Mutation returns the TradeDecisionMutation object of the builder.
func (_u *TradeDecisionUpdate) Mutation() *TradeDecisionMutation {
	return _u.mutation
}

// ClearCandidate clears the "candidate" edge to the Candidate entity.
func (_u *TradeDecisionUpdate) ClearCandidate() *TradeDecisionUpdate {
	_u.mutation.ClearCandidate()
	return _u
}

// ClearPosition clears the "position" edge to the PaperPosition entity.
func (_u *TradeDecisionUpdate) ClearPosition() *TradeDecisionUpdate {
	_u.mutation.ClearPosition()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TradeDecisionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TradeDecisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TradeDecisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TradeDecisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TradeDecisionUpdate) check() error {
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := tradedecision.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "TradeDecision.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Outcome(); ok {
		if err := tradedecision.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "TradeDecision.outcome": %w`, err)}
		}
	}
	if _u.mutation.CandidateCleared() && len(_u.mutation.CandidateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TradeDecision.candidate"`)
	}
	return nil
}

func (_u *TradeDecisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tradedecision.Table, tradedecision.Columns, sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(tradedecision.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(tradedecision.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleResults(); ok {
		_spec.SetField(tradedecision.FieldRuleResults, field.TypeJSON, value)
	}
	if _u.mutation.CandidateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradedecision.CandidateTable,
			Columns: []string{tradedecision.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradedecision.CandidateTable,
			Columns: []string{tradedecision.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tradedecision.PositionTable,
			Columns: []string{tradedecision.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tradedecision.PositionTable,
			Columns: []string{tradedecision.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tradedecision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TradeDecisionUpdateOne is the builder for updating a single TradeDecision entity.
type TradeDecisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TradeDecisionMutation
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *TradeDecisionUpdateOne) SetIdempotencyKey(v string) *TradeDecisionUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *TradeDecisionUpdateOne) SetNillableIdempotencyKey(v *string) *TradeDecisionUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *TradeDecisionUpdateOne) SetOutcome(v string) *TradeDecisionUpdateOne {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *TradeDecisionUpdateOne) SetNillableOutcome(v *string) *TradeDecisionUpdateOne {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetRuleResults sets the "rule_results" field.
func (_u *TradeDecisionUpdateOne) SetRuleResults(v map[string]interface{}) *TradeDecisionUpdateOne {
	_u.mutation.SetRuleResults(v)
	return _u
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_u *TradeDecisionUpdateOne) SetCandidateID(id int) *TradeDecisionUpdateOne {
	_u.mutation.SetCandidateID(id)
	return _u
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_u *TradeDecisionUpdateOne) SetCandidate(v *Candidate) *TradeDecisionUpdateOne {
	return _u.SetCandidateID(v.ID)
}

// SetPositionID sets the "position" edge to the PaperPosition entity by ID.
func (_u *TradeDecisionUpdateOne) SetPositionID(id int) *TradeDecisionUpdateOne {
	_u.mutation.SetPositionID(id)
	return _u
}

// SetNillablePositionID sets the "position" edge to the PaperPosition entity by ID if the given value is not nil.
func (_u *TradeDecisionUpdateOne) SetNillablePositionID(id *int) *TradeDecisionUpdateOne {
	if id != nil {
		_u = _u.SetPositionID(*id)
	}
	return _u
}

// SetPosition sets the "position" edge to the PaperPosition entity.
func (_u *TradeDecisionUpdateOne) SetPosition(v *PaperPosition) *TradeDecisionUpdateOne {
	return _u.SetPositionID(v.ID)
}

// Mutation returns the TradeDecisionMutation object of the builder.
func (_u *TradeDecisionUpdateOne) Mutation() *TradeDecisionMutation {
	return _u.mutation
}

// ClearCandidate clears the "candidate" edge to the Candidate entity.
func (_u *TradeDecisionUpdateOne) ClearCandidate() *TradeDecisionUpdateOne {
	_u.mutation.ClearCandidate()
	return _u
}

// ClearPosition clears the "position" edge to the PaperPosition entity.
func (_u *TradeDecisionUpdateOne) ClearPosition() *TradeDecisionUpdateOne {
	_u.mutation.ClearPosition()
	return _u
}

// Where appends a list predicates to the TradeDecisionUpdate builder.
func (_u *TradeDecisionUpdateOne) Where(ps ...predicate.TradeDecision) *TradeDecisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TradeDecisionUpdateOne) Select(field string, fields ...string) *TradeDecisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TradeDecision entity.
func (_u *TradeDecisionUpdateOne) Save(ctx context.Context) (*TradeDecision, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TradeDecisionUpdateOne) SaveX(ctx context.Context) *TradeDecision {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TradeDecisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TradeDecisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TradeDecisionUpdateOne) check() error {
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := tradedecision.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "TradeDecision.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Outcome(); ok {
		if err := tradedecision.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "TradeDecision.outcome": %w`, err)}
		}
	}
	if _u.mutation.CandidateCleared() && len(_u.mutation.CandidateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TradeDecision.candidate"`)
	}
	return nil
}

func (_u *TradeDecisionUpdateOne) sqlSave(ctx context.Context) (_node *TradeDecision, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tradedecision.Table, tradedecision.Columns, sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TradeDecision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tradedecision.FieldID)
		for _, f := range fields {
			if !tradedecision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tradedecision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(tradedecision.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(tradedecision.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleResults(); ok {
		_spec.SetField(tradedecision.FieldRuleResults, field.TypeJSON, value)
	}
	if _u.mutation.CandidateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradedecision.CandidateTable,
			Columns: []string{tradedecision.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradedecision.CandidateTable,
			Columns: []string{tradedecision.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tradedecision.PositionTable,
			Columns: []string{tradedecision.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tradedecision.PositionTable,
			Columns: []string{tradedecision.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TradeDecision{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tradedecision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
