// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/verdict"
)

// VerdictCreate is the builder for creating a Verdict entity.
type VerdictCreate struct {
	config
	mutation *VerdictMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProvider sets the "provider" field.
func (_c *VerdictCreate) SetProvider(v string) *VerdictCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *VerdictCreate) SetModel(v string) *VerdictCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *VerdictCreate) SetOutcome(v string) *VerdictCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetEvidence sets the "evidence" field.
func (_c *VerdictCreate) SetEvidence(v map[string]interface{}) *VerdictCreate {
	_c.mutation.SetEvidence(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VerdictCreate) SetCreatedAt(v time.Time) *VerdictCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VerdictCreate) SetNillableCreatedAt(v *time.Time) *VerdictCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_c *VerdictCreate) SetCandidateID(id int) *VerdictCreate {
	_c.mutation.SetCandidateID(id)
	return _c
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_c *VerdictCreate) SetCandidate(v *Candidate) *VerdictCreate {
	return _c.SetCandidateID(v.ID)
}

// Mutation returns the VerdictMutation object of the builder.
func (_c *VerdictCreate) Mutation() *VerdictMutation {
	return _c.mutation
}

// Save creates the Verdict in the database.
func (_c *VerdictCreate) Save(ctx context.Context) (*Verdict, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VerdictCreate) SaveX(ctx context.Context) *Verdict {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VerdictCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VerdictCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VerdictCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := verdict.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VerdictCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "Verdict.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := verdict.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Verdict.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "Verdict.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := verdict.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Verdict.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "Verdict.outcome"`)}
	}
	if v, ok := _c.mutation.Outcome(); ok {
		if err := verdict.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "Verdict.outcome": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Evidence(); !ok {
		return &ValidationError{Name: "evidence", err: errors.New(`ent: missing required field "Verdict.evidence"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Verdict.created_at"`)}
	}
	if len(_c.mutation.CandidateIDs()) == 0 {
		return &ValidationError{Name: "candidate", err: errors.New(`ent: missing required edge "Verdict.candidate"`)}
	}
	return nil
}

func (_c *VerdictCreate) sqlSave(ctx context.Context) (*Verdict, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VerdictCreate) createSpec() (*Verdict, *sqlgraph.CreateSpec) {
	var (
		_node = &Verdict{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(verdict.Table, sqlgraph.NewFieldSpec(verdict.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(verdict.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(verdict.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(verdict.FieldOutcome, field.TypeString, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.Evidence(); ok {
		_spec.SetField(verdict.FieldEvidence, field.TypeJSON, value)
		_node.Evidence = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(verdict.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   verdict.CandidateTable,
			Columns: []string{verdict.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.candidate_verdicts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Verdict.Create().
//		SetProvider(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VerdictUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *VerdictCreate) OnConflict(opts ...sql.ConflictOption) *VerdictUpsertOne {
	_c.conflict = opts
	return &VerdictUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Verdict.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VerdictCreate) OnConflictColumns(columns ...string) *VerdictUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VerdictUpsertOne{
		create: _c,
	}
}

type (
	// VerdictUpsertOne is the builder for "upsert"-ing
	//  one Verdict node.
	VerdictUpsertOne struct {
		create *VerdictCreate
	}

	// VerdictUpsert is the "OnConflict" setter.
	VerdictUpsert struct {
		*sql.UpdateSet
	}
)

// SetProvider sets the "provider" field.
func (u *VerdictUpsert) SetProvider(v string) *VerdictUpsert {
	u.Set(verdict.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *VerdictUpsert) UpdateProvider() *VerdictUpsert {
	u.SetExcluded(verdict.FieldProvider)
	return u
}

// SetModel sets the "model" field.
func (u *VerdictUpsert) SetModel(v string) *VerdictUpsert {
	u.Set(verdict.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VerdictUpsert) UpdateModel() *VerdictUpsert {
	u.SetExcluded(verdict.FieldModel)
	return u
}

// SetOutcome sets the "outcome" field.
func (u *VerdictUpsert) SetOutcome(v string) *VerdictUpsert {
	u.Set(verdict.FieldOutcome, v)
	return u
}

// UpdateOutcome sets the "outcome" field to the value that was provided on create.
func (u *VerdictUpsert) UpdateOutcome() *VerdictUpsert {
	u.SetExcluded(verdict.FieldOutcome)
	return u
}

// SetEvidence sets the "evidence" field.
func (u *VerdictUpsert) SetEvidence(v map[string]interface{}) *VerdictUpsert {
	u.Set(verdict.FieldEvidence, v)
	return u
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *VerdictUpsert) UpdateEvidence() *VerdictUpsert {
	u.SetExcluded(verdict.FieldEvidence)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Verdict.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VerdictUpsertOne) UpdateNewValues() *VerdictUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(verdict.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Verdict.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VerdictUpsertOne) Ignore() *VerdictUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VerdictUpsertOne) DoNothing() *VerdictUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VerdictCreate.OnConflict
// documentation for more info.
func (u *VerdictUpsertOne) Update(set func(*VerdictUpsert)) *VerdictUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VerdictUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *VerdictUpsertOne) SetProvider(v string) *VerdictUpsertOne {
	return u.Update(func(s *VerdictUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *VerdictUpsertOne) UpdateProvider() *VerdictUpsertOne {
	return u.Update(func(s *VerdictUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *VerdictUpsertOne) SetModel(v string) *VerdictUpsertOne {
	return u.Update(func(s *VerdictUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VerdictUpsertOne) UpdateModel() *VerdictUpsertOne {
	return u.Update(func(s *VerdictUpsert) {
		s.UpdateModel()
	})
}

// SetOutcome sets the "outcome" field.
func (u *VerdictUpsertOne) SetOutcome(v string) *VerdictUpsertOne {
	return u.Update(func(s *VerdictUpsert) {
		s.SetOutcome(v)
	})
}

// UpdateOutcome sets the "outcome" field to the value that was provided on create.
func (u *VerdictUpsertOne) UpdateOutcome() *VerdictUpsertOne {
	return u.Update(func(s *VerdictUpsert) {
		s.UpdateOutcome()
	})
}

// SetEvidence sets the "evidence" field.
func (u *VerdictUpsertOne) SetEvidence(v map[string]interface{}) *VerdictUpsertOne {
	return u.Update(func(s *VerdictUpsert) {
		s.SetEvidence(v)
	})
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *VerdictUpsertOne) UpdateEvidence() *VerdictUpsertOne {
	return u.Update(func(s *VerdictUpsert) {
		s.UpdateEvidence()
	})
}

// Exec executes the query.
func (u *VerdictUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VerdictCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VerdictUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VerdictUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VerdictUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VerdictCreateBulk is the builder for creating many Verdict entities in bulk.
type VerdictCreateBulk struct {
	config
	err      error
	builders []*VerdictCreate
	conflict []sql.ConflictOption
}

// Save creates the Verdict entities in the database.
func (_c *VerdictCreateBulk) Save(ctx context.Context) ([]*Verdict, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Verdict, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VerdictMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VerdictCreateBulk) SaveX(ctx context.Context) []*Verdict {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VerdictCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VerdictCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Verdict.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VerdictUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *VerdictCreateBulk) OnConflict(opts ...sql.ConflictOption) *VerdictUpsertBulk {
	_c.conflict = opts
	return &VerdictUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Verdict.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VerdictCreateBulk) OnConflictColumns(columns ...string) *VerdictUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VerdictUpsertBulk{
		create: _c,
	}
}

// VerdictUpsertBulk is the builder for "upsert"-ing
// a bulk of Verdict nodes.
type VerdictUpsertBulk struct {
	create *VerdictCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Verdict.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VerdictUpsertBulk) UpdateNewValues() *VerdictUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(verdict.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Verdict.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VerdictUpsertBulk) Ignore() *VerdictUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VerdictUpsertBulk) DoNothing() *VerdictUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VerdictCreateBulk.OnConflict
// documentation for more info.
func (u *VerdictUpsertBulk) Update(set func(*VerdictUpsert)) *VerdictUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VerdictUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *VerdictUpsertBulk) SetProvider(v string) *VerdictUpsertBulk {
	return u.Update(func(s *VerdictUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *VerdictUpsertBulk) UpdateProvider() *VerdictUpsertBulk {
	return u.Update(func(s *VerdictUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *VerdictUpsertBulk) SetModel(v string) *VerdictUpsertBulk {
	return u.Update(func(s *VerdictUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VerdictUpsertBulk) UpdateModel() *VerdictUpsertBulk {
	return u.Update(func(s *VerdictUpsert) {
		s.UpdateModel()
	})
}

// SetOutcome sets the "outcome" field.
func (u *VerdictUpsertBulk) SetOutcome(v string) *VerdictUpsertBulk {
	return u.Update(func(s *VerdictUpsert) {
		s.SetOutcome(v)
	})
}

// UpdateOutcome sets the "outcome" field to the value that was provided on create.
func (u *VerdictUpsertBulk) UpdateOutcome() *VerdictUpsertBulk {
	return u.Update(func(s *VerdictUpsert) {
		s.UpdateOutcome()
	})
}

// SetEvidence sets the "evidence" field.
func (u *VerdictUpsertBulk) SetEvidence(v map[string]interface{}) *VerdictUpsertBulk {
	return u.Update(func(s *VerdictUpsert) {
		s.SetEvidence(v)
	})
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *VerdictUpsertBulk) UpdateEvidence() *VerdictUpsertBulk {
	return u.Update(func(s *VerdictUpsert) {
		s.UpdateEvidence()
	})
}

// Exec executes the query.
func (u *VerdictUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VerdictCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VerdictCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VerdictUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
