// Code generated by ent, DO NOT EDIT.

package apiusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/solana-market-research/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldProvider, v))
}

// UtcDate applies equality check predicate on the "utc_date" field. It's identical to UtcDateEQ.
func UtcDate(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldUtcDate, v))
}

// RequestCount applies equality check predicate on the "request_count" field. It's identical to RequestCountEQ.
func RequestCount(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldRequestCount, v))
}

// FailureCount applies equality check predicate on the "failure_count" field. It's identical to FailureCountEQ.
func FailureCount(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldFailureCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldContainsFold(FieldProvider, v))
}

// UtcDateEQ applies the EQ predicate on the "utc_date" field.
func UtcDateEQ(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldUtcDate, v))
}

// UtcDateNEQ applies the NEQ predicate on the "utc_date" field.
func UtcDateNEQ(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNEQ(FieldUtcDate, v))
}

// UtcDateIn applies the In predicate on the "utc_date" field.
func UtcDateIn(vs ...time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldIn(FieldUtcDate, vs...))
}

// UtcDateNotIn applies the NotIn predicate on the "utc_date" field.
func UtcDateNotIn(vs ...time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNotIn(FieldUtcDate, vs...))
}

// UtcDateGT applies the GT predicate on the "utc_date" field.
func UtcDateGT(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGT(FieldUtcDate, v))
}

// UtcDateGTE applies the GTE predicate on the "utc_date" field.
func UtcDateGTE(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGTE(FieldUtcDate, v))
}

// UtcDateLT applies the LT predicate on the "utc_date" field.
func UtcDateLT(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLT(FieldUtcDate, v))
}

// UtcDateLTE applies the LTE predicate on the "utc_date" field.
func UtcDateLTE(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLTE(FieldUtcDate, v))
}

// RequestCountEQ applies the EQ predicate on the "request_count" field.
func RequestCountEQ(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldRequestCount, v))
}

// RequestCountNEQ applies the NEQ predicate on the "request_count" field.
func RequestCountNEQ(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNEQ(FieldRequestCount, v))
}

// RequestCountIn applies the In predicate on the "request_count" field.
func RequestCountIn(vs ...int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldIn(FieldRequestCount, vs...))
}

// RequestCountNotIn applies the NotIn predicate on the "request_count" field.
func RequestCountNotIn(vs ...int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNotIn(FieldRequestCount, vs...))
}

// RequestCountGT applies the GT predicate on the "request_count" field.
func RequestCountGT(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGT(FieldRequestCount, v))
}

// RequestCountGTE applies the GTE predicate on the "request_count" field.
func RequestCountGTE(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGTE(FieldRequestCount, v))
}

// RequestCountLT applies the LT predicate on the "request_count" field.
func RequestCountLT(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLT(FieldRequestCount, v))
}

// RequestCountLTE applies the LTE predicate on the "request_count" field.
func RequestCountLTE(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLTE(FieldRequestCount, v))
}

// FailureCountEQ applies the EQ predicate on the "failure_count" field.
func FailureCountEQ(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldFailureCount, v))
}

// FailureCountNEQ applies the NEQ predicate on the "failure_count" field.
func FailureCountNEQ(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNEQ(FieldFailureCount, v))
}

// FailureCountIn applies the In predicate on the "failure_count" field.
func FailureCountIn(vs ...int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldIn(FieldFailureCount, vs...))
}

// FailureCountNotIn applies the NotIn predicate on the "failure_count" field.
func FailureCountNotIn(vs ...int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNotIn(FieldFailureCount, vs...))
}

// FailureCountGT applies the GT predicate on the "failure_count" field.
func FailureCountGT(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGT(FieldFailureCount, v))
}

// FailureCountGTE applies the GTE predicate on the "failure_count" field.
func FailureCountGTE(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGTE(FieldFailureCount, v))
}

// FailureCountLT applies the LT predicate on the "failure_count" field.
func FailureCountLT(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLT(FieldFailureCount, v))
}

// FailureCountLTE applies the LTE predicate on the "failure_count" field.
func FailureCountLTE(v int) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLTE(FieldFailureCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIUsage {
	return predicate.APIUsage(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIUsage) predicate.APIUsage {
	return predicate.APIUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIUsage) predicate.APIUsage {
	return predicate.APIUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIUsage) predicate.APIUsage {
	return predicate.APIUsage(sql.NotPredicates(p))
}
